"""Stub file for custom_components/reflex_nivo/base.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
import re
from reflex.components.component import Component
from reflex.utils.imports import ImportDict

_SERIALIZE_JS = '\nconst reflexNivoSerialize = (value, depth = 0, seen = new WeakSet()) => {\n  if (value === null || value === undefined) return null;\n  const kind = typeof value;\n  if (kind === "number") return Number.isFinite(value) ? value : null;\n  if (kind === "string" || kind === "boolean") return value;\n  if (kind === "bigint") return value.toString();\n  if (kind === "function" || kind === "symbol") return undefined;\n  if (value instanceof Date) return value.toISOString();\n  if (typeof Node !== "undefined" && value instanceof Node) return undefined;\n  if (typeof Event !== "undefined" && value instanceof Event) return undefined;\n  if (value.nativeEvent !== undefined && value.currentTarget !== undefined) return undefined;\n  if (seen.has(value)) return value.id !== undefined ? reflexNivoSerialize(value.id, depth, seen) : undefined;\n  if (depth > 6) return undefined;\n  seen.add(value);\n  if (Array.isArray(value)) {\n    return value.slice(0, 2000).map((item) => {\n      const serialized = reflexNivoSerialize(item, depth + 1, seen);\n      return serialized === undefined ? null : serialized;\n    });\n  }\n  const result = {};\n  for (const key of Object.keys(value)) {\n    const serialized = reflexNivoSerialize(value[key], depth + 1, seen);\n    if (serialized !== undefined) result[key] = serialized;\n  }\n  return result;\n};\n'
_TEMPLATE_JS = '\nconst reflexNivoGet = (obj, path) => path.split(".").reduce((acc, key) => (acc === null || acc === undefined ? undefined : acc[key]), obj);\nconst reflexNivoEscape = (text) => String(text).replace(/[&<>"\']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", \'"\': "&quot;", "\'": "&#39;" })[c]);\nconst reflexNivoFormat = (template, source, escape) => String(template).replace(/\\{\\s*([\\w$.]+)\\s*\\}/g, (_, path) => {\n  const raw = reflexNivoGet(source, path);\n  const text = raw === null || raw === undefined ? "" : (typeof raw === "object" ? JSON.stringify(reflexNivoSerialize(raw)) : String(raw));\n  return escape ? reflexNivoEscape(text) : text;\n});\nconst reflexNivoTemplateCache = new Map();\nconst reflexNivoTemplate = (template) => {\n  const cacheKey = "template:" + template;\n  if (!reflexNivoTemplateCache.has(cacheKey)) {\n    reflexNivoTemplateCache.set(cacheKey, (source) => reflexNivoFormat(template, source, false));\n  }\n  return reflexNivoTemplateCache.get(cacheKey);\n};\nconst reflexNivoTooltip = (template, style) => {\n  const cacheKey = "tooltip:" + template + "::" + JSON.stringify(style || {});\n  if (!reflexNivoTemplateCache.has(cacheKey)) {\n    const NivoTemplateTooltip = (props) => {\n      const theme = reflexNivoUseTheme();\n      const container = (theme && theme.tooltip && theme.tooltip.container) || {};\n      return reflexNivoCreateElement("div", {\n        style: { ...container, whiteSpace: "pre", ...(style || {}) },\n        dangerouslySetInnerHTML: { __html: reflexNivoFormat(template, props, true) },\n      });\n    };\n    reflexNivoTemplateCache.set(cacheKey, NivoTemplateTooltip);\n  }\n  return reflexNivoTemplateCache.get(cacheKey);\n};\n'

def nivo_event_spec(datum: Var[Any]) -> tuple[Var[dict[str, Any]]]: ...

_ISO_DATE = re.compile("\\d{4}-\\d{2}-\\d{2}")
_CONTAINER_PROPS = frozenset({"id", "class_name", "style", "title", "tab_index"})

class NivoComponent(Component):
    def add_imports(self) -> ImportDict: ...
    def add_custom_code(self) -> list[str]: ...
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "NivoComponent":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

__all__ = ["NivoComponent", "nivo_event_spec"]
