"""Reflex wrappers for @nivo/bar.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class Bar(NivoComponent):
    """Bar chart (grouped/stacked, vertical/horizontal).

    Wraps ``ResponsiveBar`` from ``@nivo/bar``.
    Docs: https://nivo.rocks/bar/
    """

    library = nivo_package("bar")
    tag = "ResponsiveBar"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: boolean | undefined
    animate_on_mount: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: ((data: ComputedDatum<D>) => string | undefined) | undefined
    bar_aria_described_by: Var[Any]
    # TS: ((data: ComputedDatum<D>) => Booleanish | undefined) | undefined
    bar_aria_disabled: Var[Any]
    # TS: ((data: ComputedDatum<D>) => Booleanish | undefined) | undefined
    bar_aria_hidden: Var[Any]
    # TS: ((data: ComputedDatum<D>) => string | undefined) | undefined
    bar_aria_label: Var[Any]
    # TS: ((data: ComputedDatum<D>) => string | undefined) | undefined
    bar_aria_labelled_by: Var[Any]
    # TS: BarComponent<D> | undefined
    bar_component: Var[Any]
    # TS: string | ((data: ComputedDatum<D>) => string) | undefined
    bar_role: Var[Any]
    # TS: InheritedColorConfig<ComputedBarDatumWithValue<D>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: "id" | "indexValue" | undefined
    color_by: Var[Literal["id", "indexValue"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: boolean | undefined
    enable_totals: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: GridValues<string | number> | undefined
    grid_x_values: Var[Any]
    # TS: GridValues<string | number> | undefined
    grid_y_values: Var[Any]
    # TS: "grouped" | "stacked" | undefined
    group_mode: Var[Literal["grouped", "stacked"]]
    # TS: PropertyAccessor<D, string> | undefined
    index_by: Var[Any]
    # TS: ScaleBandSpec | undefined
    index_scale: Var[Any]
    # TS: readonly (string | number)[] | undefined
    initial_hidden_ids: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # TS: boolean | undefined
    is_focusable: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: readonly string[] | undefined
    keys: Var[Sequence[str]]
    # TS: PropertyAccessor<ComputedDatum<D>, string> | undefined
    label: Var[Any]
    # TS: string | LabelFormatter | undefined
    label_format: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: "start" | "middle" | "end" | undefined
    label_position: Var[Literal["start", "middle", "end"]]
    # TS: number | undefined
    label_skip_height: Var[int | float]
    # TS: number | undefined
    label_skip_width: Var[int | float]
    # TS: InheritedColorConfig<ComputedBarDatumWithValue<D>> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical" | undefined
    layout: Var[Literal["horizontal", "vertical"]]
    # TS: PropertyAccessor<LegendLabelDatum<D>, string> | undefined
    legend_label: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # Cartesian markers: [{'axis': 'y', 'value': 0, 'legend': '...'}].
    markers: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    padding: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<ComputedDatum<D>, string> | undefined
    tooltip_label: Var[Any]
    # TS: number | undefined
    totals_offset: Var[int | float]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: ScaleLinearSpec | ScaleSymlogSpec | undefined
    value_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class BarCanvas(NivoComponent):
    """Bar chart rendered on canvas, for large datasets.

    Wraps ``ResponsiveBarCanvas`` from ``@nivo/bar``.
    Docs: https://nivo.rocks/bar/canvas/
    """

    library = nivo_package("bar")
    tag = "ResponsiveBarCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: InheritedColorConfig<ComputedBarDatumWithValue<D>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: "id" | "indexValue" | undefined
    color_by: Var[Literal["id", "indexValue"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: boolean | undefined
    enable_totals: Var[bool]
    # TS: GridValues<string | number> | undefined
    grid_x_values: Var[Any]
    # TS: GridValues<string | number> | undefined
    grid_y_values: Var[Any]
    # TS: "grouped" | "stacked" | undefined
    group_mode: Var[Literal["grouped", "stacked"]]
    # TS: PropertyAccessor<D, string> | undefined
    index_by: Var[Any]
    # TS: ScaleBandSpec | undefined
    index_scale: Var[Any]
    # TS: readonly (string | number)[] | undefined
    initial_hidden_ids: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: readonly string[] | undefined
    keys: Var[Sequence[str]]
    # TS: PropertyAccessor<ComputedDatum<D>, string> | undefined
    label: Var[Any]
    # TS: string | LabelFormatter | undefined
    label_format: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: "start" | "middle" | "end" | undefined
    label_position: Var[Literal["start", "middle", "end"]]
    # TS: number | undefined
    label_skip_height: Var[int | float]
    # TS: number | undefined
    label_skip_width: Var[int | float]
    # TS: InheritedColorConfig<ComputedBarDatumWithValue<D>> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical" | undefined
    layout: Var[Literal["horizontal", "vertical"]]
    # TS: PropertyAccessor<LegendLabelDatum<D>, string> | undefined
    legend_label: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | undefined
    padding: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: BarCanvasRenderer<D> | undefined
    render_bar: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<ComputedDatum<D>, string> | undefined
    tooltip_label: Var[Any]
    # TS: number | undefined
    totals_offset: Var[int | float]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: ScaleLinearSpec | ScaleSymlogSpec | undefined
    value_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


bar = Bar.create
bar_canvas = BarCanvas.create

__all__ = [
    "Bar",
    "BarCanvas",
    "bar",
    "bar_canvas",
]
