"""Stub file for custom_components/reflex_nivo/charts/boxplot.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

class BoxPlot(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_opacity: Var[float | int] | float | int | None = None,
        animate: Var[bool] | bool | None = None,
        annotations: Any | Var[Any] | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_left: Any | Var[Any] | None = None,
        axis_right: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Var[float | int] | float | int | None = None,
        border_width: Var[float | int] | float | int | None = None,
        box_plot_aria_described_by: Any | Var[Any] | None = None,
        box_plot_aria_label: Any | Var[Any] | None = None,
        box_plot_aria_labelled_by: Any | Var[Any] | None = None,
        box_plot_component: Any | Var[Any] | None = None,
        color_by: Literal["group", "subGroup"]
        | Var[Literal["group", "subGroup"]]
        | None = None,
        colors: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        enable_grid_y: Var[bool] | bool | None = None,
        fill: Any | Var[Any] | None = None,
        grid_x_values: Any | Var[Any] | None = None,
        grid_y_values: Any | Var[Any] | None = None,
        group_by: Any | Var[Any] | None = None,
        groups: Sequence[str] | Var[Sequence[str] | None] | None = None,
        inactive_opacity: Var[float | int] | float | int | None = None,
        index_scale: Any | Var[Any] | None = None,
        inner_padding: Var[float | int] | float | int | None = None,
        is_focusable: Var[bool] | bool | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        layout: Literal["horizontal", "vertical"]
        | Var[Literal["horizontal", "vertical"]]
        | None = None,
        legend_label: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        markers: Any | Var[Any] | None = None,
        max_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        median_color: Any | Var[Any] | None = None,
        median_width: Var[float | int] | float | int | None = None,
        min_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        motion_config: Any | Var[Any] | None = None,
        opacity: Var[float | int] | float | int | None = None,
        padding: Var[float | int] | float | int | None = None,
        quantiles: Sequence[float | int] | Var[Sequence[float | int]] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        sub_group_by: Any | Var[Any] | None = None,
        sub_groups: Sequence[str] | Var[Sequence[str] | None] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        tooltip_label: Any | Var[Any] | None = None,
        value: Var[str] | str | None = None,
        value_format: Any | Var[Any] | None = None,
        value_scale: Any | Var[Any] | None = None,
        whisker_color: Any | Var[Any] | None = None,
        whisker_end_size: Var[float | int] | float | int | None = None,
        whisker_width: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "BoxPlot":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_opacity: no description
            animate: no description
            annotations: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            axis_bottom: no description
            axis_left: no description
            axis_right: no description
            axis_top: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            box_plot_aria_described_by: no description
            box_plot_aria_label: no description
            box_plot_aria_labelled_by: no description
            box_plot_component: no description
            color_by: no description
            colors: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            defs: no description
            enable_grid_x: no description
            enable_grid_y: no description
            fill: no description
            grid_x_values: no description
            grid_y_values: no description
            group_by: no description
            groups: no description
            inactive_opacity: no description
            index_scale: no description
            inner_padding: no description
            is_focusable: no description
            is_interactive: no description
            layers: no description
            layout: no description
            legend_label: no description
            legends: no description
            margin: no description
            markers: no description
            max_value: no description
            median_color: no description
            median_width: no description
            min_value: no description
            motion_config: no description
            opacity: no description
            padding: no description
            quantiles: no description
            render_wrapper: no description
            role: no description
            sub_group_by: no description
            sub_groups: no description
            theme: no description
            tooltip: no description
            tooltip_label: no description
            value: no description
            value_format: no description
            value_scale: no description
            whisker_color: no description
            whisker_end_size: no description
            whisker_width: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

boxplot = BoxPlot.create
__all__ = ["BoxPlot", "boxplot"]
