"""Reflex wrappers for @nivo/boxplot.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class BoxPlot(NivoComponent):
    """Box plot showing distributions (quantiles, whiskers, outliers).

    Wraps ``ResponsiveBoxPlot`` from ``@nivo/boxplot``.
    Docs: https://nivo.rocks/boxplot/
    """

    library = nivo_package("boxplot")
    tag = "ResponsiveBoxPlot"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | undefined
    active_opacity: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: InheritedColorConfig<ComputedBoxPlotSummary> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: ((data: ComputedBoxPlotSummary) => string | undefined) | undefined
    box_plot_aria_described_by: Var[Any]
    # TS: ((data: ComputedBoxPlotSummary) => string | undefined) | undefined
    box_plot_aria_label: Var[Any]
    # TS: ((data: ComputedBoxPlotSummary) => string | undefined) | undefined
    box_plot_aria_labelled_by: Var[Any]
    # TS: FC<BoxPlotItemProps<RawDatum>> | undefined
    box_plot_component: Var[Any]
    # TS: "group" | "subGroup" | undefined
    color_by: Var[Literal["group", "subGroup"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: GridValues<string | number> | undefined
    grid_x_values: Var[Any]
    # TS: GridValues<string | number> | undefined
    grid_y_values: Var[Any]
    # TS: PropertyAccessor<RawDatum, string> | undefined
    group_by: Var[Any]
    # TS: string[] | null | undefined
    groups: Var[Sequence[str] | None]
    # TS: number | undefined
    inactive_opacity: Var[int | float]
    # TS: ScaleBandSpec | undefined
    index_scale: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # TS: boolean | undefined
    is_focusable: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical" | undefined
    layout: Var[Literal["horizontal", "vertical"]]
    # TS: PropertyAccessor<BoxPlotSummary, string> | undefined
    legend_label: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # Cartesian markers: [{'axis': 'y', 'value': 0, 'legend': '...'}].
    markers: Var[Any]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # TS: InheritedColorConfig<ComputedBoxPlotSummary> | undefined
    median_color: Var[Any]
    # TS: number | undefined
    median_width: Var[int | float]
    # TS: number | "auto" | undefined
    min_value: Var[Literal["auto"] | int | float]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    opacity: Var[int | float]
    # TS: number | undefined
    padding: Var[int | float]
    # TS: number[] | undefined
    quantiles: Var[Sequence[int | float]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: PropertyAccessor<RawDatum, string> | null | undefined
    sub_group_by: Var[Any]
    # TS: string[] | null | undefined
    sub_groups: Var[Sequence[str] | None]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<BoxPlotSummary, string> | undefined
    tooltip_label: Var[Any]
    # TS: string | undefined
    value: Var[str]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: ScaleLinearSpec | ScaleSymlogSpec | ScaleLogSpec | ScaleTimeSpec | undefined
    value_scale: Var[Any]
    # TS: InheritedColorConfig<ComputedBoxPlotSummary> | undefined
    whisker_color: Var[Any]
    # TS: number | undefined
    whisker_end_size: Var[int | float]
    # TS: number | undefined
    whisker_width: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


boxplot = BoxPlot.create

__all__ = [
    "BoxPlot",
    "boxplot",
]
