"""Reflex wrappers for @nivo/bullet.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Bullet(NivoComponent):
    """Bullet charts comparing a measure against ranges and markers.

    Wraps ``ResponsiveBullet`` from ``@nivo/bullet``.
    Docs: https://nivo.rocks/bullet/
    """

    library = nivo_package("bullet")
    tag = "ResponsiveBullet"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: "before" | "after" | undefined
    axis_position: Var[Literal["before", "after"]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: "horizontal" | "vertical" | undefined
    layout: Var[Literal["horizontal", "vertical"]]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: Colors | undefined
    marker_colors: Var[Any]
    # TS: ComponentType<BulletMarkersItemProps> | undefined
    marker_component: Var[Any]
    # TS: number | undefined
    marker_size: Var[int | float]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # TS: InheritedColorConfig<ComputedRangeDatum> | undefined
    measure_border_color: Var[Any]
    # TS: number | undefined
    measure_border_width: Var[int | float]
    # TS: Colors | undefined
    measure_colors: Var[Any]
    # TS: ComponentType<BulletRectsItemProps> | undefined
    measure_component: Var[Any]
    # TS: number | undefined
    measure_size: Var[int | float]
    # TS: number | "auto" | undefined
    min_value: Var[Literal["auto"] | int | float]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: InheritedColorConfig<ComputedRangeDatum> | undefined
    range_border_color: Var[Any]
    # TS: number | undefined
    range_border_width: Var[int | float]
    # TS: Colors | undefined
    range_colors: Var[Any]
    # TS: ComponentType<BulletRectsItemProps> | undefined
    range_component: Var[Any]
    # TS: boolean | undefined
    reverse: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number | undefined
    spacing: Var[int | float]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: "start" | "middle" | "end" | undefined
    title_align: Var[Literal["start", "middle", "end"]]
    # TS: number | undefined
    title_offset_x: Var[int | float]
    # TS: number | undefined
    title_offset_y: Var[int | float]
    # TS: "before" | "after" | undefined
    title_position: Var[Literal["before", "after"]]
    # TS: number | undefined
    title_rotation: Var[int | float]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_marker_click: EventHandler[nivo_event_spec]
    on_measure_click: EventHandler[nivo_event_spec]
    on_range_click: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


bullet = Bullet.create

__all__ = [
    "Bullet",
    "bullet",
]
