"""Reflex wrappers for @nivo/bump.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class AreaBump(NivoComponent):
    """Area bump chart: ranking evolution with areas proportional to values.

    Wraps ``ResponsiveAreaBump`` from ``@nivo/bump``.
    Docs: https://nivo.rocks/area-bump/
    """

    library = nivo_package("bump")
    tag = "ResponsiveAreaBump"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | undefined
    active_border_opacity: Var[int | float]
    # TS: number | undefined
    active_border_width: Var[int | float]
    # TS: number | undefined
    active_fill_opacity: Var[int | float]
    # TS: AreaBumpAlign | undefined
    align: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: CssMixBlendMode | undefined
    blend_mode: Var[str]
    # TS: InheritedColorConfig<Omit<AreaBumpComputedSerie<Datum, ExtraProps>, "borderColor" | "borderWidth" | "fillOpaci
    border_color: Var[Any]
    # TS: number | undefined
    border_opacity: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: string[] | undefined
    default_active_serie_ids: Var[Sequence[str]]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: AreaBumpLabel<Datum, ExtraProps> | undefined
    end_label: Var[Any]
    # TS: number | undefined
    end_label_padding: Var[int | float]
    # TS: InheritedColorConfig<AreaBumpComputedSerie<Datum, ExtraProps>> | undefined
    end_label_text_color: Var[Any]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: number | undefined
    fill_opacity: Var[int | float]
    # TS: number | undefined
    inactive_border_opacity: Var[int | float]
    # TS: number | undefined
    inactive_border_width: Var[int | float]
    # TS: number | undefined
    inactive_fill_opacity: Var[int | float]
    # TS: AreaBumpInterpolation | undefined
    interpolation: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number | undefined
    spacing: Var[int | float]
    # TS: AreaBumpLabel<Datum, ExtraProps> | undefined
    start_label: Var[Any]
    # TS: number | undefined
    start_label_padding: Var[int | float]
    # TS: InheritedColorConfig<AreaBumpComputedSerie<Datum, ExtraProps>> | undefined
    start_label_text_color: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: number | undefined
    x_padding: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class Bump(NivoComponent):
    """Bump chart: ranking evolution over time.

    Wraps ``ResponsiveBump`` from ``@nivo/bump``.
    Docs: https://nivo.rocks/bump/
    """

    library = nivo_package("bump")
    tag = "ResponsiveBump"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | undefined
    active_line_width: Var[int | float]
    # TS: number | undefined
    active_opacity: Var[int | float]
    # TS: number | undefined
    active_point_border_width: Var[int | float]
    # TS: number | undefined
    active_point_size: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # TS: string[] | undefined
    default_active_serie_ids: Var[Sequence[str]]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: BumpLabel<Datum, ExtraProps> | undefined
    end_label: Var[Any]
    # TS: number | undefined
    end_label_padding: Var[int | float]
    # TS: InheritedColorConfig<BumpComputedSerie<Datum, ExtraProps>> | undefined
    end_label_text_color: Var[Any]
    # TS: number | undefined
    inactive_line_width: Var[int | float]
    # TS: number | undefined
    inactive_opacity: Var[int | float]
    # TS: number | undefined
    inactive_point_border_width: Var[int | float]
    # TS: number | undefined
    inactive_point_size: Var[int | float]
    # TS: BumpInterpolation | undefined
    interpolation: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: BumpLineTooltip<Datum, ExtraProps> | undefined
    line_tooltip: Var[Any]
    # TS: number | undefined
    line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    opacity: Var[int | float]
    # TS: InheritedColorConfig<Omit<BumpPoint<Datum, ExtraProps>, "borderColor">> | undefined
    point_border_color: Var[Any]
    # TS: number | undefined
    point_border_width: Var[int | float]
    # TS: InheritedColorConfig<Omit<BumpPoint<Datum, ExtraProps>, "borderColor" | "color">> | undefined
    point_color: Var[Any]
    # TS: BumpPointComponent<Datum, ExtraProps> | undefined
    point_component: Var[Any]
    # TS: number | undefined
    point_size: Var[int | float]
    # TS: BumpPointTooltip<Datum, ExtraProps> | undefined
    point_tooltip: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: BumpLabel<Datum, ExtraProps> | undefined
    start_label: Var[Any]
    # TS: number | undefined
    start_label_padding: Var[int | float]
    # TS: InheritedColorConfig<BumpComputedSerie<Datum, ExtraProps>> | undefined
    start_label_text_color: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]
    # TS: number | undefined
    x_outer_padding: Var[int | float]
    # TS: number | undefined
    x_padding: Var[int | float]
    # TS: number | undefined
    y_outer_padding: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_mouse_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


area_bump = AreaBump.create
bump = Bump.create

__all__ = [
    "AreaBump",
    "Bump",
    "area_bump",
    "bump",
]
