"""Stub file for custom_components/reflex_nivo/charts/bump.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

from reflex.components.component import Component


class AreaBump(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_border_opacity: Var[float | int] | float | int | None = None,
        active_border_width: Var[float | int] | float | int | None = None,
        active_fill_opacity: Var[float | int] | float | int | None = None,
        align: Any | Var[Any] | None = None,
        animate: Var[bool] | bool | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        blend_mode: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_opacity: Var[float | int] | float | int | None = None,
        border_width: Var[float | int] | float | int | None = None,
        colors: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_active_serie_ids: Sequence[str] | Var[Sequence[str]] | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        end_label: Any | Var[Any] | None = None,
        end_label_padding: Var[float | int] | float | int | None = None,
        end_label_text_color: Any | Var[Any] | None = None,
        fill: Any | Var[Any] | None = None,
        fill_opacity: Var[float | int] | float | int | None = None,
        inactive_border_opacity: Var[float | int] | float | int | None = None,
        inactive_border_width: Var[float | int] | float | int | None = None,
        inactive_fill_opacity: Var[float | int] | float | int | None = None,
        interpolation: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        spacing: Var[float | int] | float | int | None = None,
        start_label: Any | Var[Any] | None = None,
        start_label_padding: Var[float | int] | float | int | None = None,
        start_label_text_color: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        x_padding: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_border_opacity: no description
            active_border_width: no description
            active_fill_opacity: no description
            align: no description
            animate: no description
            axis_bottom: no description
            axis_top: no description
            blend_mode: no description
            border_color: no description
            border_opacity: no description
            border_width: no description
            colors: no description
            data: no description
            debounce_resize: no description
            default_active_serie_ids: no description
            default_height: no description
            default_width: no description
            defs: no description
            enable_grid_x: no description
            end_label: no description
            end_label_padding: no description
            end_label_text_color: no description
            fill: no description
            fill_opacity: no description
            inactive_border_opacity: no description
            inactive_border_width: no description
            inactive_fill_opacity: no description
            interpolation: no description
            is_interactive: no description
            layers: no description
            margin: no description
            motion_config: no description
            render_wrapper: no description
            role: no description
            spacing: no description
            start_label: no description
            start_label_padding: no description
            start_label_text_color: no description
            theme: no description
            tooltip: no description
            x_padding: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class Bump(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_line_width: Var[float | int] | float | int | None = None,
        active_opacity: Var[float | int] | float | int | None = None,
        active_point_border_width: Var[float | int] | float | int | None = None,
        active_point_size: Var[float | int] | float | int | None = None,
        animate: Var[bool] | bool | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_left: Any | Var[Any] | None = None,
        axis_right: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        debug_mesh: Var[bool] | bool | None = None,
        default_active_serie_ids: Sequence[str] | Var[Sequence[str]] | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        enable_grid_y: Var[bool] | bool | None = None,
        end_label: Any | Var[Any] | None = None,
        end_label_padding: Var[float | int] | float | int | None = None,
        end_label_text_color: Any | Var[Any] | None = None,
        inactive_line_width: Var[float | int] | float | int | None = None,
        inactive_opacity: Var[float | int] | float | int | None = None,
        inactive_point_border_width: Var[float | int] | float | int | None = None,
        inactive_point_size: Var[float | int] | float | int | None = None,
        interpolation: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        line_tooltip: Any | Var[Any] | None = None,
        line_width: Var[float | int] | float | int | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        opacity: Var[float | int] | float | int | None = None,
        point_border_color: Any | Var[Any] | None = None,
        point_border_width: Var[float | int] | float | int | None = None,
        point_color: Any | Var[Any] | None = None,
        point_component: Any | Var[Any] | None = None,
        point_size: Var[float | int] | float | int | None = None,
        point_tooltip: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        start_label: Any | Var[Any] | None = None,
        start_label_padding: Var[float | int] | float | int | None = None,
        start_label_text_color: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        use_mesh: Var[bool] | bool | None = None,
        x_outer_padding: Var[float | int] | float | int | None = None,
        x_padding: Var[float | int] | float | int | None = None,
        y_outer_padding: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_line_width: no description
            active_opacity: no description
            active_point_border_width: no description
            active_point_size: no description
            animate: no description
            axis_bottom: no description
            axis_left: no description
            axis_right: no description
            axis_top: no description
            colors: no description
            data: no description
            debounce_resize: no description
            debug_mesh: no description
            default_active_serie_ids: no description
            default_height: no description
            default_width: no description
            enable_grid_x: no description
            enable_grid_y: no description
            end_label: no description
            end_label_padding: no description
            end_label_text_color: no description
            inactive_line_width: no description
            inactive_opacity: no description
            inactive_point_border_width: no description
            inactive_point_size: no description
            interpolation: no description
            is_interactive: no description
            layers: no description
            line_tooltip: no description
            line_width: no description
            margin: no description
            motion_config: no description
            opacity: no description
            point_border_color: no description
            point_border_width: no description
            point_color: no description
            point_component: no description
            point_size: no description
            point_tooltip: no description
            render_wrapper: no description
            role: no description
            start_label: no description
            start_label_padding: no description
            start_label_text_color: no description
            theme: no description
            use_mesh: no description
            x_outer_padding: no description
            x_padding: no description
            y_outer_padding: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

area_bump = AreaBump.create
bump = Bump.create
__all__ = ["AreaBump", "Bump", "area_bump", "bump"]
