"""Stub file for custom_components/reflex_nivo/charts/calendar.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

class Calendar(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        align: Var[str] | str | None = None,
        color_scale: Any | Var[Any] | None = None,
        colors: Sequence[str] | Var[Sequence[str]] | None = None,
        data: Any | Var[Any] | None = None,
        day_border_color: Var[str] | str | None = None,
        day_border_width: Var[float | int] | float | int | None = None,
        day_spacing: Var[float | int] | float | int | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        direction: Literal["horizontal", "vertical"]
        | Var[Literal["horizontal", "vertical"]]
        | None = None,
        empty_color: Var[str] | str | None = None,
        from_date: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        legend_format: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        max_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        min_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        month_border_color: Var[str] | str | None = None,
        month_border_width: Var[float | int] | float | int | None = None,
        month_legend: Any | Var[Any] | None = None,
        month_legend_offset: Var[float | int] | float | int | None = None,
        month_legend_position: Literal["after", "before"]
        | Var[Literal["after", "before"]]
        | None = None,
        month_spacing: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        to_date: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        year_legend: Any | Var[Any] | None = None,
        year_legend_offset: Var[float | int] | float | int | None = None,
        year_legend_position: Literal["after", "before"]
        | Var[Literal["after", "before"]]
        | None = None,
        year_spacing: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Calendar":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            align: no description
            color_scale: no description
            colors: no description
            data: no description
            day_border_color: no description
            day_border_width: no description
            day_spacing: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            direction: no description
            empty_color: no description
            from_date: no description
            is_interactive: no description
            legend_format: no description
            legends: no description
            margin: no description
            max_value: no description
            min_value: no description
            month_border_color: no description
            month_border_width: no description
            month_legend: no description
            month_legend_offset: no description
            month_legend_position: no description
            month_spacing: no description
            render_wrapper: no description
            role: no description
            theme: no description
            to_date: no description
            tooltip: no description
            value_format: no description
            year_legend: no description
            year_legend_offset: no description
            year_legend_position: no description
            year_spacing: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class CalendarCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        align: Var[str] | str | None = None,
        color_scale: Any | Var[Any] | None = None,
        colors: Sequence[str] | Var[Sequence[str]] | None = None,
        data: Any | Var[Any] | None = None,
        day_border_color: Var[str] | str | None = None,
        day_border_width: Var[float | int] | float | int | None = None,
        day_spacing: Var[float | int] | float | int | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        direction: Literal["horizontal", "vertical"]
        | Var[Literal["horizontal", "vertical"]]
        | None = None,
        empty_color: Var[str] | str | None = None,
        from_date: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        legend_format: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        max_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        min_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        month_border_color: Var[str] | str | None = None,
        month_border_width: Var[float | int] | float | int | None = None,
        month_legend: Any | Var[Any] | None = None,
        month_legend_offset: Var[float | int] | float | int | None = None,
        month_legend_position: Literal["after", "before"]
        | Var[Literal["after", "before"]]
        | None = None,
        month_spacing: Var[float | int] | float | int | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        theme: Any | Var[Any] | None = None,
        to_date: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        year_legend: Any | Var[Any] | None = None,
        year_legend_offset: Var[float | int] | float | int | None = None,
        year_legend_position: Literal["after", "before"]
        | Var[Literal["after", "before"]]
        | None = None,
        year_spacing: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CalendarCanvas":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            align: no description
            color_scale: no description
            colors: no description
            data: no description
            day_border_color: no description
            day_border_width: no description
            day_spacing: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            direction: no description
            empty_color: no description
            from_date: no description
            is_interactive: no description
            legend_format: no description
            legends: no description
            margin: no description
            max_value: no description
            min_value: no description
            month_border_color: no description
            month_border_width: no description
            month_legend: no description
            month_legend_offset: no description
            month_legend_position: no description
            month_spacing: no description
            pixel_ratio: no description
            render_wrapper: no description
            theme: no description
            to_date: no description
            tooltip: no description
            value_format: no description
            year_legend: no description
            year_legend_offset: no description
            year_legend_position: no description
            year_spacing: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class TimeRange(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        align: Var[str] | str | None = None,
        color_scale: Any | Var[Any] | None = None,
        colors: Sequence[str] | Var[Sequence[str]] | None = None,
        data: Any | Var[Any] | None = None,
        day_border_color: Var[str] | str | None = None,
        day_border_width: Var[float | int] | float | int | None = None,
        day_radius: Var[float | int] | float | int | None = None,
        day_spacing: Var[float | int] | float | int | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        direction: Literal["horizontal", "vertical"]
        | Var[Literal["horizontal", "vertical"]]
        | None = None,
        empty_color: Var[str] | str | None = None,
        first_weekday: Any | Var[Any] | None = None,
        from_date: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        legend_format: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        max_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        min_value: Literal["auto"]
        | Var[Literal["auto"] | float | int]
        | float
        | int
        | None = None,
        month_legend: Any | Var[Any] | None = None,
        month_legend_offset: Var[float | int] | float | int | None = None,
        month_legend_position: Literal["after", "before"]
        | Var[Literal["after", "before"]]
        | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        square: Var[bool] | bool | None = None,
        theme: Any | Var[Any] | None = None,
        to_date: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        weekday_legend_offset: Var[float | int] | float | int | None = None,
        weekday_ticks: Any | Var[Any] | None = None,
        weekdays: Sequence[str] | Var[Sequence[str]] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TimeRange":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            align: no description
            color_scale: no description
            colors: no description
            data: no description
            day_border_color: no description
            day_border_width: no description
            day_radius: no description
            day_spacing: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            direction: no description
            empty_color: no description
            first_weekday: no description
            from_date: no description
            is_interactive: no description
            legend_format: no description
            legends: no description
            margin: no description
            max_value: no description
            min_value: no description
            month_legend: no description
            month_legend_offset: no description
            month_legend_position: no description
            render_wrapper: no description
            role: no description
            square: no description
            theme: no description
            to_date: no description
            tooltip: no description
            value_format: no description
            weekday_legend_offset: no description
            weekday_ticks: no description
            weekdays: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

calendar = Calendar.create
calendar_canvas = CalendarCanvas.create
time_range = TimeRange.create
__all__ = [
    "Calendar",
    "CalendarCanvas",
    "TimeRange",
    "calendar",
    "calendar_canvas",
    "time_range",
]
