"""Reflex wrappers for @nivo/calendar.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Calendar(NivoComponent):
    """Calendar heatmap of daily values across years.

    Wraps ``ResponsiveCalendar`` from ``@nivo/calendar``.
    Docs: https://nivo.rocks/calendar/
    """

    library = nivo_package("calendar")
    tag = "ResponsiveCalendar"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: BoxAlign | undefined
    align: Var[str]
    # TS: ColorScale | undefined
    color_scale: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Sequence[str]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # TS: string | undefined
    day_border_color: Var[str]
    # TS: number | undefined
    day_border_width: Var[int | float]
    # TS: number | undefined
    day_spacing: Var[int | float]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: "horizontal" | "vertical" | undefined
    direction: Var[Literal["horizontal", "vertical"]]
    # TS: string | undefined
    empty_color: Var[str]
    # Start date (nivo's `from` prop), 'YYYY-MM-DD'. (required)
    from_date: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: ValueFormat<number> | undefined
    legend_format: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # TS: number | "auto" | undefined
    min_value: Var[Literal["auto"] | int | float]
    # TS: string | undefined
    month_border_color: Var[str]
    # TS: number | undefined
    month_border_width: Var[int | float]
    # TS: ((year: number, month: number, date: Date) => string | number) | undefined
    month_legend: Var[Any]
    # TS: number | undefined
    month_legend_offset: Var[int | float]
    # TS: "before" | "after" | undefined
    month_legend_position: Var[Literal["before", "after"]]
    # TS: number | undefined
    month_spacing: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # End date (nivo's `to` prop), 'YYYY-MM-DD'. (required)
    to_date: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: ((year: number) => string | number) | undefined
    year_legend: Var[Any]
    # TS: number | undefined
    year_legend_offset: Var[int | float]
    # TS: "before" | "after" | undefined
    year_legend_position: Var[Literal["before", "after"]]
    # TS: number | undefined
    year_spacing: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class CalendarCanvas(NivoComponent):
    """Calendar heatmap rendered on canvas.

    Wraps ``ResponsiveCalendarCanvas`` from ``@nivo/calendar``.
    Docs: https://nivo.rocks/calendar/canvas/
    """

    library = nivo_package("calendar")
    tag = "ResponsiveCalendarCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: BoxAlign | undefined
    align: Var[str]
    # TS: ColorScale | undefined
    color_scale: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Sequence[str]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # TS: string | undefined
    day_border_color: Var[str]
    # TS: number | undefined
    day_border_width: Var[int | float]
    # TS: number | undefined
    day_spacing: Var[int | float]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: "horizontal" | "vertical" | undefined
    direction: Var[Literal["horizontal", "vertical"]]
    # TS: string | undefined
    empty_color: Var[str]
    # Start date (nivo's `from` prop), 'YYYY-MM-DD'. (required)
    from_date: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: ValueFormat<number> | undefined
    legend_format: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # TS: number | "auto" | undefined
    min_value: Var[Literal["auto"] | int | float]
    # TS: string | undefined
    month_border_color: Var[str]
    # TS: number | undefined
    month_border_width: Var[int | float]
    # TS: ((year: number, month: number, date: Date) => string | number) | undefined
    month_legend: Var[Any]
    # TS: number | undefined
    month_legend_offset: Var[int | float]
    # TS: "before" | "after" | undefined
    month_legend_position: Var[Literal["before", "after"]]
    # TS: number | undefined
    month_spacing: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # End date (nivo's `to` prop), 'YYYY-MM-DD'. (required)
    to_date: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: ((year: number) => string | number) | undefined
    year_legend: Var[Any]
    # TS: number | undefined
    year_legend_offset: Var[int | float]
    # TS: "before" | "after" | undefined
    year_legend_position: Var[Literal["before", "after"]]
    # TS: number | undefined
    year_spacing: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class TimeRange(NivoComponent):
    """Calendar-like heatmap over an arbitrary date range.

    Wraps ``ResponsiveTimeRange`` from ``@nivo/calendar``.
    Docs: https://nivo.rocks/time-range/
    """

    library = nivo_package("calendar")
    tag = "ResponsiveTimeRange"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: BoxAlign | undefined
    align: Var[str]
    # TS: ColorScale | undefined
    color_scale: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Sequence[str]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # TS: string | undefined
    day_border_color: Var[str]
    # TS: number | undefined
    day_border_width: Var[int | float]
    # TS: number | undefined
    day_radius: Var[int | float]
    # TS: number | undefined
    day_spacing: Var[int | float]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: "horizontal" | "vertical" | undefined
    direction: Var[Literal["horizontal", "vertical"]]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: Weekday | undefined
    first_weekday: Var[Any]
    # Start date (nivo's `from` prop), 'YYYY-MM-DD'.
    from_date: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: ValueFormat<number> | undefined
    legend_format: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # TS: number | "auto" | undefined
    min_value: Var[Literal["auto"] | int | float]
    # TS: ((year: number, month: number, date: Date) => string | number) | undefined
    month_legend: Var[Any]
    # TS: number | undefined
    month_legend_offset: Var[int | float]
    # TS: "before" | "after" | undefined
    month_legend_position: Var[Literal["before", "after"]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: boolean | undefined
    square: Var[bool]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # End date (nivo's `to` prop), 'YYYY-MM-DD'.
    to_date: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: number | undefined
    weekday_legend_offset: Var[int | float]
    # TS: (0 | 1 | 2 | 3 | 4 | 5 | 6)[] | undefined
    weekday_ticks: Var[Any]
    # TS: string[] | undefined
    weekdays: Var[Sequence[str]]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


calendar = Calendar.create
calendar_canvas = CalendarCanvas.create
time_range = TimeRange.create

__all__ = [
    "Calendar",
    "CalendarCanvas",
    "TimeRange",
    "calendar",
    "calendar_canvas",
    "time_range",
]
