"""Reflex wrappers for @nivo/chord.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Chord(NivoComponent):
    """Chord diagram of flows between groups (square matrix).

    Wraps ``ResponsiveChord`` from ``@nivo/chord``.
    Docs: https://nivo.rocks/chord/
    """

    library = nivo_package("chord")
    tag = "ResponsiveChord"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | undefined
    active_arc_opacity: Var[int | float]
    # TS: number | undefined
    active_ribbon_opacity: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    arc_border_color: Var[Any]
    # TS: number | undefined
    arc_border_width: Var[int | float]
    # TS: number | undefined
    arc_opacity: Var[int | float]
    # TS: ArcTooltipComponent | undefined
    arc_tooltip: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: number | undefined
    inactive_arc_opacity: Var[int | float]
    # TS: number | undefined
    inactive_ribbon_opacity: Var[int | float]
    # TS: number | undefined
    inner_radius_offset: Var[int | float]
    # TS: number | undefined
    inner_radius_ratio: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: string[] (required)
    keys: Var[Sequence[str]]
    # TS: PropertyAccessor<Omit<ArcDatum, "label" | "color">, string> | undefined
    label: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: number | undefined
    label_rotation: Var[int | float]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    pad_angle: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # TS: CssMixBlendMode | undefined
    ribbon_blend_mode: Var[str]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    ribbon_border_color: Var[Any]
    # TS: number | undefined
    ribbon_border_width: Var[int | float]
    # TS: number | undefined
    ribbon_opacity: Var[int | float]
    # TS: RibbonTooltipComponent | undefined
    ribbon_tooltip: Var[Any]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_arc_click: EventHandler[nivo_event_spec]
    on_arc_mouse_enter: EventHandler[nivo_event_spec]
    on_arc_mouse_leave: EventHandler[nivo_event_spec]
    on_arc_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]
    on_ribbon_click: EventHandler[nivo_event_spec]
    on_ribbon_mouse_enter: EventHandler[nivo_event_spec]
    on_ribbon_mouse_leave: EventHandler[nivo_event_spec]
    on_ribbon_mouse_move: EventHandler[nivo_event_spec]


class ChordCanvas(NivoComponent):
    """Chord diagram rendered on canvas.

    Wraps ``ResponsiveChordCanvas`` from ``@nivo/chord``.
    Docs: https://nivo.rocks/chord/canvas/
    """

    library = nivo_package("chord")
    tag = "ResponsiveChordCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: number | undefined
    active_arc_opacity: Var[int | float]
    # TS: number | undefined
    active_ribbon_opacity: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    arc_border_color: Var[Any]
    # TS: number | undefined
    arc_border_width: Var[int | float]
    # TS: number | undefined
    arc_opacity: Var[int | float]
    # TS: ArcTooltipComponent | undefined
    arc_tooltip: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: number | undefined
    inactive_arc_opacity: Var[int | float]
    # TS: number | undefined
    inactive_ribbon_opacity: Var[int | float]
    # TS: number | undefined
    inner_radius_offset: Var[int | float]
    # TS: number | undefined
    inner_radius_ratio: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: string[] (required)
    keys: Var[Sequence[str]]
    # TS: PropertyAccessor<Omit<ArcDatum, "label" | "color">, string> | undefined
    label: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: number | undefined
    label_rotation: Var[int | float]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    pad_angle: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # TS: CssMixBlendMode | undefined
    ribbon_blend_mode: Var[str]
    # TS: InheritedColorConfig<ArcDatum> | undefined
    ribbon_border_color: Var[Any]
    # TS: number | undefined
    ribbon_border_width: Var[int | float]
    # TS: number | undefined
    ribbon_opacity: Var[int | float]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_arc_click: EventHandler[nivo_event_spec]
    on_arc_mouse_enter: EventHandler[nivo_event_spec]
    on_arc_mouse_leave: EventHandler[nivo_event_spec]
    on_arc_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


chord = Chord.create
chord_canvas = ChordCanvas.create

__all__ = [
    "Chord",
    "ChordCanvas",
    "chord",
    "chord_canvas",
]
