"""Stub file for custom_components/reflex_nivo/charts/geo.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

from reflex.components.component import Component


class Choropleth(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        defs: Any | Var[Any] | None = None,
        domain: Sequence[float | int] | Var[Sequence[float | int]] | None = None,
        enable_graticule: Var[bool] | bool | None = None,
        features: Any | Var[Any] | None = None,
        fill: Any | Var[Any] | None = None,
        graticule_line_color: Var[str] | str | None = None,
        graticule_line_width: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        match: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        projection_rotation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_scale: Var[float | int] | float | int | None = None,
        projection_translation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_type: Literal[
            "azimuthalEqualArea",
            "azimuthalEquidistant",
            "equalEarth",
            "equirectangular",
            "gnomonic",
            "mercator",
            "naturalEarth1",
            "orthographic",
            "stereographic",
            "transverseMercator",
        ]
        | Var[
            Literal[
                "azimuthalEqualArea",
                "azimuthalEquidistant",
                "equalEarth",
                "equirectangular",
                "gnomonic",
                "mercator",
                "naturalEarth1",
                "orthographic",
                "stereographic",
                "transverseMercator",
            ]
        ]
        | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        unknown_color: Var[str] | str | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            border_color: no description
            border_width: no description
            colors: no description
            data: no description
            defs: no description
            domain: no description
            enable_graticule: no description
            features: no description
            fill: no description
            graticule_line_color: no description
            graticule_line_width: no description
            is_interactive: no description
            label: no description
            layers: no description
            legends: no description
            margin: no description
            match: no description
            motion_config: no description
            projection_rotation: no description
            projection_scale: no description
            projection_translation: no description
            projection_type: no description
            render_wrapper: no description
            role: no description
            theme: no description
            tooltip: no description
            unknown_color: no description
            value: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class ChoroplethCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        defs: Any | Var[Any] | None = None,
        domain: Sequence[float | int] | Var[Sequence[float | int]] | None = None,
        enable_graticule: Var[bool] | bool | None = None,
        features: Any | Var[Any] | None = None,
        fill: Any | Var[Any] | None = None,
        graticule_line_color: Var[str] | str | None = None,
        graticule_line_width: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        match: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        projection_rotation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_scale: Var[float | int] | float | int | None = None,
        projection_translation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_type: Literal[
            "azimuthalEqualArea",
            "azimuthalEquidistant",
            "equalEarth",
            "equirectangular",
            "gnomonic",
            "mercator",
            "naturalEarth1",
            "orthographic",
            "stereographic",
            "transverseMercator",
        ]
        | Var[
            Literal[
                "azimuthalEqualArea",
                "azimuthalEquidistant",
                "equalEarth",
                "equirectangular",
                "gnomonic",
                "mercator",
                "naturalEarth1",
                "orthographic",
                "stereographic",
                "transverseMercator",
            ]
        ]
        | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        unknown_color: Var[str] | str | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            border_color: no description
            border_width: no description
            colors: no description
            data: no description
            defs: no description
            domain: no description
            enable_graticule: no description
            features: no description
            fill: no description
            graticule_line_color: no description
            graticule_line_width: no description
            is_interactive: no description
            label: no description
            layers: no description
            legends: no description
            margin: no description
            match: no description
            motion_config: no description
            pixel_ratio: no description
            projection_rotation: no description
            projection_scale: no description
            projection_translation: no description
            projection_type: no description
            render_wrapper: no description
            theme: no description
            tooltip: no description
            unknown_color: no description
            value: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class GeoMap(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Any | Var[Any] | None = None,
        defs: Any | Var[Any] | None = None,
        enable_graticule: Var[bool] | bool | None = None,
        features: Any | Var[Any] | None = None,
        fill: Any | Var[Any] | None = None,
        fill_color: Any | Var[Any] | None = None,
        graticule_line_color: Var[str] | str | None = None,
        graticule_line_width: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        projection_rotation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_scale: Var[float | int] | float | int | None = None,
        projection_translation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_type: Literal[
            "azimuthalEqualArea",
            "azimuthalEquidistant",
            "equalEarth",
            "equirectangular",
            "gnomonic",
            "mercator",
            "naturalEarth1",
            "orthographic",
            "stereographic",
            "transverseMercator",
        ]
        | Var[
            Literal[
                "azimuthalEqualArea",
                "azimuthalEquidistant",
                "equalEarth",
                "equirectangular",
                "gnomonic",
                "mercator",
                "naturalEarth1",
                "orthographic",
                "stereographic",
                "transverseMercator",
            ]
        ]
        | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            border_color: no description
            border_width: no description
            defs: no description
            enable_graticule: no description
            features: no description
            fill: no description
            fill_color: no description
            graticule_line_color: no description
            graticule_line_width: no description
            is_interactive: no description
            layers: no description
            legends: no description
            margin: no description
            motion_config: no description
            projection_rotation: no description
            projection_scale: no description
            projection_translation: no description
            projection_type: no description
            render_wrapper: no description
            role: no description
            theme: no description
            tooltip: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class GeoMapCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Any | Var[Any] | None = None,
        defs: Any | Var[Any] | None = None,
        enable_graticule: Var[bool] | bool | None = None,
        features: Any | Var[Any] | None = None,
        fill: Any | Var[Any] | None = None,
        fill_color: Any | Var[Any] | None = None,
        graticule_line_color: Var[str] | str | None = None,
        graticule_line_width: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        projection_rotation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_scale: Var[float | int] | float | int | None = None,
        projection_translation: Sequence[float | int]
        | Var[Sequence[float | int]]
        | None = None,
        projection_type: Literal[
            "azimuthalEqualArea",
            "azimuthalEquidistant",
            "equalEarth",
            "equirectangular",
            "gnomonic",
            "mercator",
            "naturalEarth1",
            "orthographic",
            "stereographic",
            "transverseMercator",
        ]
        | Var[
            Literal[
                "azimuthalEqualArea",
                "azimuthalEquidistant",
                "equalEarth",
                "equirectangular",
                "gnomonic",
                "mercator",
                "naturalEarth1",
                "orthographic",
                "stereographic",
                "transverseMercator",
            ]
        ]
        | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            border_color: no description
            border_width: no description
            defs: no description
            enable_graticule: no description
            features: no description
            fill: no description
            fill_color: no description
            graticule_line_color: no description
            graticule_line_width: no description
            is_interactive: no description
            layers: no description
            legends: no description
            margin: no description
            motion_config: no description
            pixel_ratio: no description
            projection_rotation: no description
            projection_scale: no description
            projection_translation: no description
            projection_type: no description
            render_wrapper: no description
            theme: no description
            tooltip: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

choropleth = Choropleth.create
choropleth_canvas = ChoroplethCanvas.create
geo_map = GeoMap.create
geo_map_canvas = GeoMapCanvas.create
__all__ = [
    "Choropleth",
    "ChoroplethCanvas",
    "GeoMap",
    "GeoMapCanvas",
    "choropleth",
    "choropleth_canvas",
    "geo_map",
    "geo_map_canvas",
]
