"""Reflex wrappers for @nivo/geo.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class Choropleth(NivoComponent):
    """Choropleth map: GeoJSON features colored by value.

    Wraps ``ResponsiveChoropleth`` from ``@nivo/geo``.
    Docs: https://nivo.rocks/choropleth/
    """

    library = nivo_package("geo")
    tag = "ResponsiveChoropleth"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    border_color: Var[Any]
    # TS: number | FeatureAccessor<Feature, number>
    border_width: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: number[] (required)
    domain: Var[Sequence[int | float]]
    # TS: boolean
    enable_graticule: Var[bool]
    # TS: any[] (required)
    features: Var[Any]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: string
    graticule_line_color: Var[str]
    # TS: number
    graticule_line_width: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    label: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: string | DatumMatcher
    match: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: [number, number, number]
    projection_rotation: Var[Sequence[int | float]]
    # TS: number
    projection_scale: Var[int | float]
    # TS: [number, number]
    projection_translation: Var[Sequence[int | float]]
    # TS: "azimuthalEqualArea" | "azimuthalEquidistant" | "gnomonic" | "orthographic" | "stereographic" | "equalEarth" |
    projection_type: Var[Literal["azimuthalEqualArea", "azimuthalEquidistant", "gnomonic", "orthographic", "stereographic", "equalEarth", "equirectangular", "mercator", "transverseMercator", "naturalEarth1"]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: string
    unknown_color: Var[str]
    # TS: string | FeatureAccessor<Feature, number>
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]


class ChoroplethCanvas(NivoComponent):
    """Choropleth map rendered on canvas.

    Wraps ``ResponsiveChoroplethCanvas`` from ``@nivo/geo``.
    Docs: https://nivo.rocks/choropleth/canvas/
    """

    library = nivo_package("geo")
    tag = "ResponsiveChoroplethCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    border_color: Var[Any]
    # TS: number | FeatureAccessor<Feature, number>
    border_width: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # TS: number[] (required)
    domain: Var[Sequence[int | float]]
    # TS: boolean
    enable_graticule: Var[bool]
    # TS: any[] (required)
    features: Var[Any]
    # TS: string
    graticule_line_color: Var[str]
    # TS: number
    graticule_line_width: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    label: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: string | DatumMatcher
    match: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: [number, number, number]
    projection_rotation: Var[Sequence[int | float]]
    # TS: number
    projection_scale: Var[int | float]
    # TS: [number, number]
    projection_translation: Var[Sequence[int | float]]
    # TS: "azimuthalEqualArea" | "azimuthalEquidistant" | "gnomonic" | "orthographic" | "stereographic" | "equalEarth" |
    projection_type: Var[Literal["azimuthalEqualArea", "azimuthalEquidistant", "gnomonic", "orthographic", "stereographic", "equalEarth", "equirectangular", "mercator", "transverseMercator", "naturalEarth1"]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: string
    unknown_color: Var[str]
    # TS: string | FeatureAccessor<Feature, number>
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]


class GeoMap(NivoComponent):
    """Geographic map of GeoJSON features.

    Wraps ``ResponsiveGeoMap`` from ``@nivo/geo``.
    Docs: https://nivo.rocks/geomap/
    """

    library = nivo_package("geo")
    tag = "ResponsiveGeoMap"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    border_color: Var[Any]
    # TS: number | FeatureAccessor<Feature, number>
    border_width: Var[Any]
    # TS: boolean
    enable_graticule: Var[bool]
    # TS: any[] (required)
    features: Var[Any]
    # TS: string | FeatureAccessor<Feature, string>
    fill_color: Var[Any]
    # TS: string
    graticule_line_color: Var[str]
    # TS: number
    graticule_line_width: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: [number, number, number]
    projection_rotation: Var[Sequence[int | float]]
    # TS: number
    projection_scale: Var[int | float]
    # TS: [number, number]
    projection_translation: Var[Sequence[int | float]]
    # TS: "azimuthalEqualArea" | "azimuthalEquidistant" | "gnomonic" | "orthographic" | "stereographic" | "equalEarth" |
    projection_type: Var[Literal["azimuthalEqualArea", "azimuthalEquidistant", "gnomonic", "orthographic", "stereographic", "equalEarth", "equirectangular", "mercator", "transverseMercator", "naturalEarth1"]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]


class GeoMapCanvas(NivoComponent):
    """Geographic map rendered on canvas.

    Wraps ``ResponsiveGeoMapCanvas`` from ``@nivo/geo``.
    Docs: https://nivo.rocks/geomap/canvas/
    """

    library = nivo_package("geo")
    tag = "ResponsiveGeoMapCanvas"
    _nivo_variant: ClassVar[str] = "canvas"
    _default_props: ClassVar[dict[str, Any]] = {'layers': ['graticule', 'features']}

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | FeatureAccessor<Feature, string>
    border_color: Var[Any]
    # TS: number | FeatureAccessor<Feature, number>
    border_width: Var[Any]
    # TS: boolean
    enable_graticule: Var[bool]
    # TS: any[] (required)
    features: Var[Any]
    # TS: string | FeatureAccessor<Feature, string>
    fill_color: Var[Any]
    # TS: string
    graticule_line_color: Var[str]
    # TS: number
    graticule_line_width: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: [number, number, number]
    projection_rotation: Var[Sequence[int | float]]
    # TS: number
    projection_scale: Var[int | float]
    # TS: [number, number]
    projection_translation: Var[Sequence[int | float]]
    # TS: "azimuthalEqualArea" | "azimuthalEquidistant" | "gnomonic" | "orthographic" | "stereographic" | "equalEarth" |
    projection_type: Var[Literal["azimuthalEqualArea", "azimuthalEquidistant", "gnomonic", "orthographic", "stereographic", "equalEarth", "equirectangular", "mercator", "transverseMercator", "naturalEarth1"]]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]


choropleth = Choropleth.create
choropleth_canvas = ChoroplethCanvas.create
geo_map = GeoMap.create
geo_map_canvas = GeoMapCanvas.create

__all__ = [
    "Choropleth",
    "ChoroplethCanvas",
    "GeoMap",
    "GeoMapCanvas",
    "choropleth",
    "choropleth_canvas",
    "geo_map",
    "geo_map_canvas",
]
