"""Reflex wrappers for @nivo/heatmap.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class HeatMap(NivoComponent):
    """Heatmap of a matrix of values.

    Wraps ``ResponsiveHeatMap`` from ``@nivo/heatmap``.
    Docs: https://nivo.rocks/heatmap/
    """

    library = nivo_package("heatmap")
    tag = "ResponsiveHeatMap"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | undefined
    active_opacity: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedCell<Datum>, "borderColor">> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: CellShape | CellComponent<Datum> | undefined
    cell_component: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    force_square: Var[bool]
    # TS: "cell" | "row" | "column" | "rowColumn" | undefined
    hover_target: Var[Literal["cell", "row", "column", "rowColumn"]]
    # TS: number | undefined
    inactive_opacity: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<ComputedCell<Datum>, "borderColor" | "label" | "labelTextColor" | "color" | "opacity">, 
    label: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedCell<Datum>, "labelTextColor">> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    opacity: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: false | SizeVariationConfig | undefined
    size_variation: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: number | undefined
    x_inner_padding: Var[int | float]
    # TS: number | undefined
    x_outer_padding: Var[int | float]
    # TS: number | undefined
    y_inner_padding: Var[int | float]
    # TS: number | undefined
    y_outer_padding: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class HeatMapCanvas(NivoComponent):
    """Heatmap rendered on canvas.

    Wraps ``ResponsiveHeatMapCanvas`` from ``@nivo/heatmap``.
    Docs: https://nivo.rocks/heatmap/canvas/
    """

    library = nivo_package("heatmap")
    tag = "ResponsiveHeatMapCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: number | undefined
    active_opacity: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedCell<Datum>, "borderColor">> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    force_square: Var[bool]
    # TS: "cell" | "row" | "column" | "rowColumn" | undefined
    hover_target: Var[Literal["cell", "row", "column", "rowColumn"]]
    # TS: number | undefined
    inactive_opacity: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<ComputedCell<Datum>, "borderColor" | "label" | "labelTextColor" | "color" | "opacity">, 
    label: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedCell<Datum>, "labelTextColor">> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    opacity: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: CellShape | CellCanvasRenderer<Datum> | undefined
    render_cell: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: false | SizeVariationConfig | undefined
    size_variation: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: number | undefined
    x_inner_padding: Var[int | float]
    # TS: number | undefined
    x_outer_padding: Var[int | float]
    # TS: number | undefined
    y_inner_padding: Var[int | float]
    # TS: number | undefined
    y_outer_padding: Var[int | float]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


heatmap = HeatMap.create
heatmap_canvas = HeatMapCanvas.create

__all__ = [
    "HeatMap",
    "HeatMapCanvas",
    "heatmap",
    "heatmap_canvas",
]
