"""Stub file for custom_components/reflex_nivo/charts/icicle.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

from reflex.components.component import Component


class Icicle(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        animate_on_mount: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Any | Var[Any] | None = None,
        border_width: Var[float | int] | float | int | None = None,
        child_color: Any | Var[Any] | None = None,
        color_by: Literal["depth", "id"] | Var[Literal["depth", "id"]] | None = None,
        colors: Any | Var[Any] | None = None,
        context: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        enable_labels: Var[bool] | bool | None = None,
        enable_zooming: Var[bool] | bool | None = None,
        fill: Any | Var[Any] | None = None,
        gap_x: Var[float | int] | float | int | None = None,
        gap_y: Var[float | int] | float | int | None = None,
        identity: Any | Var[Any] | None = None,
        inherit_color_from_parent: Var[bool] | bool | None = None,
        is_focusable: Var[bool] | bool | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        label_align: Any | Var[Any] | None = None,
        label_baseline: Any | Var[Any] | None = None,
        label_box_anchor: Any | Var[Any] | None = None,
        label_component: Any | Var[Any] | None = None,
        label_offset_x: Var[float | int] | float | int | None = None,
        label_offset_y: Var[float | int] | float | int | None = None,
        label_padding_x: Var[float | int] | float | int | None = None,
        label_padding_y: Var[float | int] | float | int | None = None,
        label_rotation: Var[float | int] | float | int | None = None,
        label_skip_height: Var[float | int] | float | int | None = None,
        label_skip_width: Var[float | int] | float | int | None = None,
        label_text_color: Any | Var[Any] | None = None,
        labels_transition_mode: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        node_aria_described_by: Any | Var[Any] | None = None,
        node_aria_hidden: Any | Var[Any] | None = None,
        node_aria_label: Any | Var[Any] | None = None,
        node_aria_labelled_by: Any | Var[Any] | None = None,
        node_component: Any | Var[Any] | None = None,
        node_role: Any | Var[Any] | None = None,
        orientation: Any | Var[Any] | None = None,
        rects_transition_mode: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        sort: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        zoom_mode: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_double_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_focus: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_key_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        on_wheel: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            animate_on_mount: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            child_color: no description
            color_by: no description
            colors: no description
            context: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            defs: no description
            enable_labels: no description
            enable_zooming: no description
            fill: no description
            gap_x: no description
            gap_y: no description
            identity: no description
            inherit_color_from_parent: no description
            is_focusable: no description
            is_interactive: no description
            label: no description
            label_align: no description
            label_baseline: no description
            label_box_anchor: no description
            label_component: no description
            label_offset_x: no description
            label_offset_y: no description
            label_padding_x: no description
            label_padding_y: no description
            label_rotation: no description
            label_skip_height: no description
            label_skip_width: no description
            label_text_color: no description
            labels_transition_mode: no description
            layers: no description
            margin: no description
            motion_config: no description
            node_aria_described_by: no description
            node_aria_hidden: no description
            node_aria_label: no description
            node_aria_labelled_by: no description
            node_component: no description
            node_role: no description
            orientation: no description
            rects_transition_mode: no description
            render_wrapper: no description
            role: no description
            sort: no description
            theme: no description
            tooltip: no description
            value: no description
            value_format: no description
            zoom_mode: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_key_down: no description
            on_resize: no description
            on_wheel: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class IcicleHtml(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        animate_on_mount: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Any | Var[Any] | None = None,
        border_width: Var[float | int] | float | int | None = None,
        child_color: Any | Var[Any] | None = None,
        color_by: Literal["depth", "id"] | Var[Literal["depth", "id"]] | None = None,
        colors: Any | Var[Any] | None = None,
        context: Any | Var[Any] | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_labels: Var[bool] | bool | None = None,
        enable_zooming: Var[bool] | bool | None = None,
        gap_x: Var[float | int] | float | int | None = None,
        gap_y: Var[float | int] | float | int | None = None,
        identity: Any | Var[Any] | None = None,
        inherit_color_from_parent: Var[bool] | bool | None = None,
        is_focusable: Var[bool] | bool | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        label_align: Any | Var[Any] | None = None,
        label_baseline: Any | Var[Any] | None = None,
        label_box_anchor: Any | Var[Any] | None = None,
        label_component: Any | Var[Any] | None = None,
        label_offset_x: Var[float | int] | float | int | None = None,
        label_offset_y: Var[float | int] | float | int | None = None,
        label_padding_x: Var[float | int] | float | int | None = None,
        label_padding_y: Var[float | int] | float | int | None = None,
        label_rotation: Var[float | int] | float | int | None = None,
        label_skip_height: Var[float | int] | float | int | None = None,
        label_skip_width: Var[float | int] | float | int | None = None,
        label_text_color: Any | Var[Any] | None = None,
        labels_transition_mode: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        node_aria_described_by: Any | Var[Any] | None = None,
        node_aria_hidden: Any | Var[Any] | None = None,
        node_aria_label: Any | Var[Any] | None = None,
        node_aria_labelled_by: Any | Var[Any] | None = None,
        node_component: Any | Var[Any] | None = None,
        node_role: Any | Var[Any] | None = None,
        orientation: Any | Var[Any] | None = None,
        rects_transition_mode: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        sort: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        zoom_mode: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_double_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_focus: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_key_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        on_wheel: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            animate_on_mount: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            child_color: no description
            color_by: no description
            colors: no description
            context: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            enable_labels: no description
            enable_zooming: no description
            gap_x: no description
            gap_y: no description
            identity: no description
            inherit_color_from_parent: no description
            is_focusable: no description
            is_interactive: no description
            label: no description
            label_align: no description
            label_baseline: no description
            label_box_anchor: no description
            label_component: no description
            label_offset_x: no description
            label_offset_y: no description
            label_padding_x: no description
            label_padding_y: no description
            label_rotation: no description
            label_skip_height: no description
            label_skip_width: no description
            label_text_color: no description
            labels_transition_mode: no description
            layers: no description
            margin: no description
            motion_config: no description
            node_aria_described_by: no description
            node_aria_hidden: no description
            node_aria_label: no description
            node_aria_labelled_by: no description
            node_component: no description
            node_role: no description
            orientation: no description
            rects_transition_mode: no description
            render_wrapper: no description
            role: no description
            sort: no description
            theme: no description
            tooltip: no description
            value: no description
            value_format: no description
            zoom_mode: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_key_down: no description
            on_resize: no description
            on_wheel: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

icicle = Icicle.create
icicle_html = IcicleHtml.create
__all__ = ["Icicle", "IcicleHtml", "icicle", "icicle_html"]
