"""Reflex wrappers for @nivo/icicle.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Icicle(NivoComponent):
    """Icicle (partition) chart of hierarchical data.

    Wraps ``ResponsiveIcicle`` from ``@nivo/icicle``.
    Docs: https://nivo.rocks/icicle/
    """

    library = nivo_package("icicle")
    tag = "ResponsiveIcicle"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: boolean | undefined
    animate_on_mount: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<IcicleNode<Datum>> | undefined
    border_color: Var[Any]
    # TS: BorderRadius | undefined
    border_radius: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: InheritedColorConfig<IcicleNode<Datum>> | undefined
    child_color: Var[Any]
    # TS: "id" | "depth" | undefined
    color_by: Var[Literal["id", "depth"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: Context | undefined
    context: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    enable_zooming: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: number | undefined
    gap_x: Var[int | float]
    # TS: number | undefined
    gap_y: Var[int | float]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: boolean | undefined
    inherit_color_from_parent: Var[bool]
    # TS: boolean | undefined
    is_focusable: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<IcicleNode<Datum>, "rect">, string> | undefined
    label: Var[Any]
    # TS: "auto" | TextAlign | undefined
    label_align: Var[Any]
    # TS: "auto" | TextBaseline | undefined
    label_baseline: Var[Any]
    # TS: BoxAnchor | undefined
    label_box_anchor: Var[Any]
    # TS: RectLabelComponent<IcicleNode<Datum>> | undefined
    label_component: Var[Any]
    # TS: number | undefined
    label_offset_x: Var[int | float]
    # TS: number | undefined
    label_offset_y: Var[int | float]
    # TS: number | undefined
    label_padding_x: Var[int | float]
    # TS: number | undefined
    label_padding_y: Var[int | float]
    # TS: number | undefined
    label_rotation: Var[int | float]
    # TS: number | undefined
    label_skip_height: Var[int | float]
    # TS: number | undefined
    label_skip_width: Var[int | float]
    # TS: InheritedColorConfig<Omit<IcicleNode<Datum>, "rect">> | undefined
    label_text_color: Var[Any]
    # TS: RectTransitionMode | undefined
    labels_transition_mode: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_described_by: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => Booleanish | undefined) | undefined
    node_aria_hidden: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_label: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_labelled_by: Var[Any]
    # TS: IcicleNodeComponent<Datum> | undefined
    node_component: Var[Any]
    # TS: string | ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_role: Var[Any]
    # TS: IcicleOrientation | undefined
    orientation: Var[Any]
    # TS: RectTransitionMode | undefined
    rects_transition_mode: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: NodesSorting<Datum> | undefined
    sort: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<Datum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: IcicleZoomMode | undefined
    zoom_mode: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_blur: EventHandler[nivo_event_spec]
    on_click: EventHandler[nivo_event_spec]
    on_context_menu: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_focus: EventHandler[nivo_event_spec]
    on_key_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]
    on_wheel: EventHandler[nivo_event_spec]


class IcicleHtml(NivoComponent):
    """Icicle chart rendered with HTML elements.

    Wraps ``ResponsiveIcicleHtml`` from ``@nivo/icicle``.
    Docs: https://nivo.rocks/icicle/html/
    """

    library = nivo_package("icicle")
    tag = "ResponsiveIcicleHtml"
    _nivo_variant: ClassVar[str] = "html"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: boolean | undefined
    animate_on_mount: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<IcicleNode<Datum>> | undefined
    border_color: Var[Any]
    # TS: BorderRadius | undefined
    border_radius: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: InheritedColorConfig<IcicleNode<Datum>> | undefined
    child_color: Var[Any]
    # TS: "id" | "depth" | undefined
    color_by: Var[Literal["id", "depth"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: Context | undefined
    context: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    enable_zooming: Var[bool]
    # TS: number | undefined
    gap_x: Var[int | float]
    # TS: number | undefined
    gap_y: Var[int | float]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: boolean | undefined
    inherit_color_from_parent: Var[bool]
    # TS: boolean | undefined
    is_focusable: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<IcicleNode<Datum>, "rect">, string> | undefined
    label: Var[Any]
    # TS: "auto" | TextAlign | undefined
    label_align: Var[Any]
    # TS: "auto" | TextBaseline | undefined
    label_baseline: Var[Any]
    # TS: BoxAnchor | undefined
    label_box_anchor: Var[Any]
    # TS: RectLabelComponent<IcicleNode<Datum>> | undefined
    label_component: Var[Any]
    # TS: number | undefined
    label_offset_x: Var[int | float]
    # TS: number | undefined
    label_offset_y: Var[int | float]
    # TS: number | undefined
    label_padding_x: Var[int | float]
    # TS: number | undefined
    label_padding_y: Var[int | float]
    # TS: number | undefined
    label_rotation: Var[int | float]
    # TS: number | undefined
    label_skip_height: Var[int | float]
    # TS: number | undefined
    label_skip_width: Var[int | float]
    # TS: InheritedColorConfig<Omit<IcicleNode<Datum>, "rect">> | undefined
    label_text_color: Var[Any]
    # TS: RectTransitionMode | undefined
    labels_transition_mode: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_described_by: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => Booleanish | undefined) | undefined
    node_aria_hidden: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_label: Var[Any]
    # TS: ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_aria_labelled_by: Var[Any]
    # TS: IcicleNodeComponent<Datum> | undefined
    node_component: Var[Any]
    # TS: string | ((node: IcicleNode<Datum>) => string | undefined) | undefined
    node_role: Var[Any]
    # TS: IcicleOrientation | undefined
    orientation: Var[Any]
    # TS: RectTransitionMode | undefined
    rects_transition_mode: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: NodesSorting<Datum> | undefined
    sort: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<Datum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]
    # TS: IcicleZoomMode | undefined
    zoom_mode: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_blur: EventHandler[nivo_event_spec]
    on_click: EventHandler[nivo_event_spec]
    on_context_menu: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_focus: EventHandler[nivo_event_spec]
    on_key_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]
    on_wheel: EventHandler[nivo_event_spec]


icicle = Icicle.create
icicle_html = IcicleHtml.create

__all__ = [
    "Icicle",
    "IcicleHtml",
    "icicle",
    "icicle_html",
]
