"""Reflex wrappers for @nivo/line.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Line(NivoComponent):
    """Line/area chart with linear, point, log or time scales.

    Wraps ``ResponsiveLine`` from ``@nivo/line``.
    Docs: https://nivo.rocks/line/
    """

    library = nivo_package("line")
    tag = "ResponsiveLine"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: InferY<Series> | undefined
    area_baseline_value: Var[Any]
    # TS: CssMixBlendMode | undefined
    area_blend_mode: Var[str]
    # TS: number | undefined
    area_opacity: Var[int | float]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: CrosshairType | undefined
    crosshair_type: Var[str]
    # TS: LineCurveFactoryId | undefined
    curve: Var[str]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # TS: boolean | undefined
    debug_slices: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_area: Var[bool]
    # TS: boolean | undefined
    enable_crosshair: Var[bool]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_point_label: Var[bool]
    # TS: boolean | undefined
    enable_points: Var[bool]
    # TS: false | "x" | "y" | undefined
    enable_slices: Var[Literal["x", "y"] | bool]
    # TS: boolean | undefined
    enable_touch_crosshair: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: TicksSpec<InferX<Series>> | undefined
    grid_x_values: Var[Any]
    # TS: TicksSpec<InferY<Series>> | undefined
    grid_y_values: Var[Any]
    # TS: readonly InferSeriesId<Series>[] | undefined
    initial_hidden_ids: Var[Any]
    # TS: boolean | undefined
    is_focusable: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # TS: number | undefined
    line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # Cartesian markers: [{'axis': 'y', 'value': 0, 'legend': '...'}].
    markers: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: ((point: Point<Series>) => string | undefined) | undefined
    point_aria_described_by: Var[Any]
    # TS: ((point: Point<Series>) => Booleanish | undefined) | undefined
    point_aria_disabled: Var[Any]
    # TS: ((point: Point<Series>) => Booleanish | undefined) | undefined
    point_aria_hidden: Var[Any]
    # TS: ((point: Point<Series>) => string | undefined) | undefined
    point_aria_label: Var[Any]
    # TS: ((point: Point<Series>) => string | undefined) | undefined
    point_aria_labelled_by: Var[Any]
    # TS: InheritedColorConfig<Omit<Point<Series>, "borderColor">> | undefined
    point_border_color: Var[Any]
    # TS: number | undefined
    point_border_width: Var[int | float]
    # TS: InheritedColorConfig<PointColorContext<Series>> | undefined
    point_color: Var[Any]
    # TS: PropertyAccessor<Point<Series>, string> | undefined
    point_label: Var[Any]
    # TS: number | undefined
    point_label_y_offset: Var[int | float]
    # TS: number | undefined
    point_size: Var[int | float]
    # TS: DotsItemSymbolComponent<Point<Series>> | undefined
    point_symbol: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: SliceTooltipComponent<Series> | undefined
    slice_tooltip: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]
    # TS: ValueFormat<InferX<Series>> | undefined
    x_format: Var[Any]
    # x scale spec, e.g. {'type': 'linear', 'min': 'auto'}.
    x_scale: Var[Any]
    # TS: ValueFormat<InferY<Series>> | undefined
    y_format: Var[Any]
    # y scale spec, e.g. {'type': 'linear', 'stacked': True}.
    y_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_mouse_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]
    on_touch_end: EventHandler[nivo_event_spec]
    on_touch_move: EventHandler[nivo_event_spec]
    on_touch_start: EventHandler[nivo_event_spec]


class LineCanvas(NivoComponent):
    """Line chart rendered on canvas.

    Wraps ``ResponsiveLineCanvas`` from ``@nivo/line``.
    Docs: https://nivo.rocks/line/canvas/
    """

    library = nivo_package("line")
    tag = "ResponsiveLineCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: InferY<Series> | undefined
    area_baseline_value: Var[Any]
    # TS: number | undefined
    area_opacity: Var[int | float]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: LineCurveFactoryId | undefined
    curve: Var[str]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_area: Var[bool]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: boolean | undefined
    enable_points: Var[bool]
    # TS: TicksSpec<InferX<Series>> | undefined
    grid_x_values: Var[Any]
    # TS: TicksSpec<InferY<Series>> | undefined
    grid_y_values: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # TS: number | undefined
    line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: InheritedColorConfig<Omit<Point<Series>, "borderColor">> | undefined
    point_border_color: Var[Any]
    # TS: number | undefined
    point_border_width: Var[int | float]
    # TS: InheritedColorConfig<PointColorContext<Series>> | undefined
    point_color: Var[Any]
    # TS: number | undefined
    point_size: Var[int | float]
    # TS: DotsItemSymbolComponent<Point<Series>> | undefined
    point_symbol: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: SliceTooltipComponent<Series> | undefined
    slice_tooltip: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: ValueFormat<InferX<Series>> | undefined
    x_format: Var[Any]
    # x scale spec, e.g. {'type': 'linear', 'min': 'auto'}.
    x_scale: Var[Any]
    # TS: ValueFormat<InferY<Series>> | undefined
    y_format: Var[Any]
    # y scale spec, e.g. {'type': 'linear', 'stacked': True}.
    y_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_mouse_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]
    on_touch_end: EventHandler[nivo_event_spec]
    on_touch_move: EventHandler[nivo_event_spec]
    on_touch_start: EventHandler[nivo_event_spec]


line = Line.create
line_canvas = LineCanvas.create

__all__ = [
    "Line",
    "LineCanvas",
    "line",
    "line_canvas",
]
