"""Stub file for custom_components/reflex_nivo/charts/line.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

from reflex.components.component import Component


class Line(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        area_baseline_value: Any | Var[Any] | None = None,
        area_blend_mode: Var[str] | str | None = None,
        area_opacity: Var[float | int] | float | int | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_left: Any | Var[Any] | None = None,
        axis_right: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        crosshair_type: Var[str] | str | None = None,
        curve: Var[str] | str | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        debug_mesh: Var[bool] | bool | None = None,
        debug_slices: Var[bool] | bool | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        enable_area: Var[bool] | bool | None = None,
        enable_crosshair: Var[bool] | bool | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        enable_grid_y: Var[bool] | bool | None = None,
        enable_point_label: Var[bool] | bool | None = None,
        enable_points: Var[bool] | bool | None = None,
        enable_slices: Literal["x", "y"]
        | Var[Literal["x", "y"] | bool]
        | bool
        | None = None,
        enable_touch_crosshair: Var[bool] | bool | None = None,
        fill: Any | Var[Any] | None = None,
        grid_x_values: Any | Var[Any] | None = None,
        grid_y_values: Any | Var[Any] | None = None,
        initial_hidden_ids: Any | Var[Any] | None = None,
        is_focusable: Var[bool] | bool | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        line_width: Var[float | int] | float | int | None = None,
        margin: Any | Var[Any] | None = None,
        markers: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        point_aria_described_by: Any | Var[Any] | None = None,
        point_aria_disabled: Any | Var[Any] | None = None,
        point_aria_hidden: Any | Var[Any] | None = None,
        point_aria_label: Any | Var[Any] | None = None,
        point_aria_labelled_by: Any | Var[Any] | None = None,
        point_border_color: Any | Var[Any] | None = None,
        point_border_width: Var[float | int] | float | int | None = None,
        point_color: Any | Var[Any] | None = None,
        point_label: Any | Var[Any] | None = None,
        point_label_y_offset: Var[float | int] | float | int | None = None,
        point_size: Var[float | int] | float | int | None = None,
        point_symbol: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        slice_tooltip: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        use_mesh: Var[bool] | bool | None = None,
        x_format: Any | Var[Any] | None = None,
        x_scale: Any | Var[Any] | None = None,
        y_format: Any | Var[Any] | None = None,
        y_scale: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_touch_end: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_touch_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_touch_start: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            area_baseline_value: no description
            area_blend_mode: no description
            area_opacity: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            axis_bottom: no description
            axis_left: no description
            axis_right: no description
            axis_top: no description
            colors: no description
            crosshair_type: no description
            curve: no description
            data: no description
            debounce_resize: no description
            debug_mesh: no description
            debug_slices: no description
            default_height: no description
            default_width: no description
            defs: no description
            enable_area: no description
            enable_crosshair: no description
            enable_grid_x: no description
            enable_grid_y: no description
            enable_point_label: no description
            enable_points: no description
            enable_slices: no description
            enable_touch_crosshair: no description
            fill: no description
            grid_x_values: no description
            grid_y_values: no description
            initial_hidden_ids: no description
            is_focusable: no description
            is_interactive: no description
            layers: no description
            legends: no description
            line_width: no description
            margin: no description
            markers: no description
            motion_config: no description
            point_aria_described_by: no description
            point_aria_disabled: no description
            point_aria_hidden: no description
            point_aria_label: no description
            point_aria_labelled_by: no description
            point_border_color: no description
            point_border_width: no description
            point_color: no description
            point_label: no description
            point_label_y_offset: no description
            point_size: no description
            point_symbol: no description
            render_wrapper: no description
            role: no description
            slice_tooltip: no description
            theme: no description
            tooltip: no description
            use_mesh: no description
            x_format: no description
            x_scale: no description
            y_format: no description
            y_scale: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            on_touch_end: no description
            on_touch_move: no description
            on_touch_start: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class LineCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        area_baseline_value: Any | Var[Any] | None = None,
        area_opacity: Var[float | int] | float | int | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_left: Any | Var[Any] | None = None,
        axis_right: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        curve: Var[str] | str | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        debug_mesh: Var[bool] | bool | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_area: Var[bool] | bool | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        enable_grid_y: Var[bool] | bool | None = None,
        enable_points: Var[bool] | bool | None = None,
        grid_x_values: Any | Var[Any] | None = None,
        grid_y_values: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        line_width: Var[float | int] | float | int | None = None,
        margin: Any | Var[Any] | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        point_border_color: Any | Var[Any] | None = None,
        point_border_width: Var[float | int] | float | int | None = None,
        point_color: Any | Var[Any] | None = None,
        point_size: Var[float | int] | float | int | None = None,
        point_symbol: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        slice_tooltip: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        x_format: Any | Var[Any] | None = None,
        x_scale: Any | Var[Any] | None = None,
        y_format: Any | Var[Any] | None = None,
        y_scale: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_touch_end: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_touch_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_touch_start: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            area_baseline_value: no description
            area_opacity: no description
            axis_bottom: no description
            axis_left: no description
            axis_right: no description
            axis_top: no description
            colors: no description
            curve: no description
            data: no description
            debounce_resize: no description
            debug_mesh: no description
            default_height: no description
            default_width: no description
            enable_area: no description
            enable_grid_x: no description
            enable_grid_y: no description
            enable_points: no description
            grid_x_values: no description
            grid_y_values: no description
            is_interactive: no description
            layers: no description
            legends: no description
            line_width: no description
            margin: no description
            pixel_ratio: no description
            point_border_color: no description
            point_border_width: no description
            point_color: no description
            point_size: no description
            point_symbol: no description
            render_wrapper: no description
            role: no description
            slice_tooltip: no description
            theme: no description
            tooltip: no description
            x_format: no description
            x_scale: no description
            y_format: no description
            y_scale: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            on_touch_end: no description
            on_touch_move: no description
            on_touch_start: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

line = Line.create
line_canvas = LineCanvas.create
__all__ = ["Line", "LineCanvas", "line", "line_canvas"]
