"""Reflex wrappers for @nivo/marimekko.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Marimekko(NivoComponent):
    """Marimekko (mosaic) chart: variable-width stacked bars.

    Wraps ``ResponsiveMarimekko`` from ``@nivo/marimekko``.
    Docs: https://nivo.rocks/marimekko/
    """

    library = nivo_package("marimekko")
    tag = "ResponsiveMarimekko"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: InheritedColorConfig<DimensionDatum<Datum>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: readonly RawDimensionDatum<Datum>[] (required)
    dimensions: Var[Any]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: readonly number[] | undefined
    grid_x_values: Var[Sequence[int | float]]
    # TS: readonly number[] | undefined
    grid_y_values: Var[Sequence[int | float]]
    # Accessor for the datum id (nivo's `id` prop): a key name or JS function. (required)
    id_by: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: Layout | undefined
    layout: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: "none" | "expand" | "diverging" | "silouhette" | "wiggle" | undefined
    offset: Var[Literal["none", "expand", "diverging", "silouhette", "wiggle"]]
    # TS: number | undefined
    outer_padding: Var[int | float]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: string | number | DatumPropertyAccessor<Datum, number> (required)
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


marimekko = Marimekko.create

__all__ = [
    "Marimekko",
    "marimekko",
]
