"""Reflex wrappers for @nivo/network.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Network(NivoComponent):
    """Force-directed network graph.

    Wraps ``ResponsiveNetwork`` from ``@nivo/network``.
    Docs: https://nivo.rocks/network/
    """

    library = nivo_package("network")
    tag = "ResponsiveNetwork"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: DerivedProp<Node, number> | undefined
    active_node_size: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: number | undefined
    centering_strength: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: string[] | undefined
    default_active_node_ids: Var[Sequence[str]]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: number | undefined
    distance_max: Var[int | float]
    # TS: number | undefined
    distance_min: Var[int | float]
    # TS: DerivedProp<Node, number> | undefined
    inactive_node_size: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: number | undefined
    iterations: Var[int | float]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: CssMixBlendMode | undefined
    link_blend_mode: Var[str]
    # TS: InheritedColorConfig<Omit<ComputedLink<Node, Link>, "color" | "thickness">> | undefined
    link_color: Var[Any]
    # TS: LinkComponent<Node, Link> | undefined
    link_component: Var[Any]
    # TS: DerivedProp<Link, number> | undefined
    link_distance: Var[Any]
    # TS: DerivedProp<Omit<ComputedLink<Node, Link>, "color" | "thickness">, number> | undefined
    link_thickness: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedNode<Node>, "borderColor" | "borderWidth" | "size">> | undefined
    node_border_color: Var[Any]
    # TS: DerivedProp<Node, number> | undefined
    node_border_width: Var[Any]
    # TS: DerivedProp<Node, string> | undefined
    node_color: Var[Any]
    # TS: NodeComponent<Node> | undefined
    node_component: Var[Any]
    # TS: DerivedProp<Node, number> | undefined
    node_size: Var[Any]
    # TS: NodeTooltip<Node> | undefined
    node_tooltip: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # TS: number | undefined
    repulsivity: Var[int | float]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class NetworkCanvas(NivoComponent):
    """Force-directed network graph rendered on canvas.

    Wraps ``ResponsiveNetworkCanvas`` from ``@nivo/network``.
    Docs: https://nivo.rocks/network/canvas/
    """

    library = nivo_package("network")
    tag = "ResponsiveNetworkCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: DerivedProp<Node, number> | undefined
    active_node_size: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: number | undefined
    centering_strength: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: string[] | undefined
    default_active_node_ids: Var[Sequence[str]]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: number | undefined
    distance_max: Var[int | float]
    # TS: number | undefined
    distance_min: Var[int | float]
    # TS: DerivedProp<Node, number> | undefined
    inactive_node_size: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: number | undefined
    iterations: Var[int | float]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedLink<Node, Link>, "color" | "thickness">> | undefined
    link_color: Var[Any]
    # TS: DerivedProp<Link, number> | undefined
    link_distance: Var[Any]
    # TS: DerivedProp<Omit<ComputedLink<Node, Link>, "color" | "thickness">, number> | undefined
    link_thickness: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: InheritedColorConfig<Omit<ComputedNode<Node>, "borderColor" | "borderWidth" | "size">> | undefined
    node_border_color: Var[Any]
    # TS: DerivedProp<Node, number> | undefined
    node_border_width: Var[Any]
    # TS: DerivedProp<Node, string> | undefined
    node_color: Var[Any]
    # TS: DerivedProp<Node, number> | undefined
    node_size: Var[Any]
    # TS: NodeTooltip<Node> | undefined
    node_tooltip: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: LinkCanvasRenderer<Node, Link> | undefined
    render_link: Var[Any]
    # TS: NodeCanvasRenderer<Node> | undefined
    render_node: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # TS: number | undefined
    repulsivity: Var[int | float]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


network = Network.create
network_canvas = NetworkCanvas.create

__all__ = [
    "Network",
    "NetworkCanvas",
    "network",
    "network_canvas",
]
