"""Reflex wrappers for @nivo/parallel-coordinates.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class ParallelCoordinates(NivoComponent):
    """Parallel coordinates for multivariate data.

    Wraps ``ResponsiveParallelCoordinates`` from ``@nivo/parallel-coordinates``.
    Docs: https://nivo.rocks/parallel-coordinates/
    """

    library = nivo_package("parallel-coordinates")
    tag = "ResponsiveParallelCoordinates"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string
    aria_described_by: Var[str]
    # TS: string
    aria_label: Var[str]
    # TS: string
    aria_labelled_by: Var[str]
    # TS: "before" | "after"
    axes_ticks_position: Var[Literal["before", "after"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: "basis" | "cardinal" | "catmullRom" | "linear" | "monotoneX" | "monotoneY" | "natural" | "step" | "stepAfter" 
    curve: Var[Literal["basis", "cardinal", "catmullRom", "linear", "monotoneX", "monotoneY", "natural", "step", "stepAfter", "stepBefore"]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: (data: LegendDatum[]) => void
    forward_legend_data: Var[Any]
    # TS: string
    group_by: Var[str]
    # TS: readonly Group[]
    groups: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical"
    layout: Var[Literal["horizontal", "vertical"]]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # TS: number
    line_opacity: Var[int | float]
    # TS: number
    line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: readonly Variable[] (required)
    variables: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_resize: EventHandler[nivo_event_spec]


class ParallelCoordinatesCanvas(NivoComponent):
    """Parallel coordinates rendered on canvas.

    Wraps ``ResponsiveParallelCoordinatesCanvas`` from ``@nivo/parallel-coordinates``.
    Docs: https://nivo.rocks/parallel-coordinates/canvas/
    """

    library = nivo_package("parallel-coordinates")
    tag = "ResponsiveParallelCoordinatesCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string
    aria_described_by: Var[str]
    # TS: string
    aria_label: Var[str]
    # TS: string
    aria_labelled_by: Var[str]
    # TS: "before" | "after"
    axes_ticks_position: Var[Literal["before", "after"]]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: "basis" | "cardinal" | "catmullRom" | "linear" | "monotoneX" | "monotoneY" | "natural" | "step" | "stepAfter" 
    curve: Var[Literal["basis", "cardinal", "catmullRom", "linear", "monotoneX", "monotoneY", "natural", "step", "stepAfter", "stepBefore"]]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: (data: LegendDatum[]) => void
    forward_legend_data: Var[Any]
    # TS: string
    group_by: Var[str]
    # TS: readonly Group[]
    groups: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical"
    layout: Var[Literal["horizontal", "vertical"]]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # TS: number
    line_opacity: Var[int | float]
    # TS: number
    line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: readonly Variable[] (required)
    variables: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_resize: EventHandler[nivo_event_spec]


parallel_coordinates = ParallelCoordinates.create
parallel_coordinates_canvas = ParallelCoordinatesCanvas.create

__all__ = [
    "ParallelCoordinates",
    "ParallelCoordinatesCanvas",
    "parallel_coordinates",
    "parallel_coordinates_canvas",
]
