"""Reflex wrappers for @nivo/pie.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Pie(NivoComponent):
    """Pie / donut chart.

    Wraps ``ResponsivePie`` from ``@nivo/pie``.
    Docs: https://nivo.rocks/pie/
    """

    library = nivo_package("pie")
    tag = "ResponsivePie"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: DatumId | null | undefined
    active_id: Var[str | int | float | None]
    # TS: number | undefined
    active_inner_radius_offset: Var[int | float]
    # TS: number | undefined
    active_outer_radius_offset: Var[int | float]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: PropertyAccessor<ComputedDatum<RawDatum>, string> | undefined
    arc_label: Var[Any]
    # TS: ArcLabelComponent<ComputedDatum<RawDatum>> | undefined
    arc_labels_component: Var[Any]
    # TS: number | undefined
    arc_labels_radius_offset: Var[int | float]
    # TS: number | undefined
    arc_labels_skip_angle: Var[int | float]
    # TS: number | undefined
    arc_labels_skip_radius: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_labels_text_color: Var[Any]
    # TS: PropertyAccessor<ComputedDatum<RawDatum>, string> | undefined
    arc_link_label: Var[Any]
    # TS: ArcLinkLabelComponent<ComputedDatum<RawDatum>> | undefined
    arc_link_label_component: Var[Any]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_link_labels_color: Var[Any]
    # TS: number | undefined
    arc_link_labels_diagonal_length: Var[int | float]
    # TS: number | undefined
    arc_link_labels_offset: Var[int | float]
    # TS: number | undefined
    arc_link_labels_skip_angle: Var[int | float]
    # TS: number | undefined
    arc_link_labels_straight_length: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_link_labels_text_color: Var[Any]
    # TS: number | undefined
    arc_link_labels_text_offset: Var[int | float]
    # TS: number | undefined
    arc_link_labels_thickness: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: ArcLinkLabelComponent<ComputedDatum<RawDatum>> | undefined
    component: Var[Any]
    # TS: number | undefined
    corner_radius: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: DatumId | null | undefined
    default_active_id: Var[str | int | float | None]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_arc_labels: Var[bool]
    # TS: boolean | undefined
    enable_arc_link_labels: Var[bool]
    # TS: number | undefined
    end_angle: Var[int | float]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: boolean | undefined
    fit: Var[bool]
    # TS: ((data: LegendDatum<RawDatum>[]) => void) | undefined
    forward_legend_data: Var[Any]
    # Accessor for the datum id (nivo's `id` prop): a key name or JS function.
    id_by: Var[Any]
    # TS: number | undefined
    inner_radius: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    pad_angle: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: boolean | undefined
    sort_by_value: Var[bool]
    # TS: number | undefined
    start_angle: Var[int | float]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: "startAngle" | "endAngle" | "innerRadius" | "middleAngle" | "centerRadius" | "outerRadius" | "pushIn" | "pushO
    transition_mode: Var[Literal["startAngle", "endAngle", "innerRadius", "middleAngle", "centerRadius", "outerRadius", "pushIn", "pushOut"]]
    # TS: PropertyAccessor<RawDatum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_active_id_change: EventHandler[nivo_event_spec]
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class PieCanvas(NivoComponent):
    """Pie / donut chart rendered on canvas.

    Wraps ``ResponsivePieCanvas`` from ``@nivo/pie``.
    Docs: https://nivo.rocks/pie/canvas/
    """

    library = nivo_package("pie")
    tag = "ResponsivePieCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: DatumId | null | undefined
    active_id: Var[str | int | float | None]
    # TS: number | undefined
    active_inner_radius_offset: Var[int | float]
    # TS: number | undefined
    active_outer_radius_offset: Var[int | float]
    # TS: PropertyAccessor<ComputedDatum<RawDatum>, string> | undefined
    arc_label: Var[Any]
    # TS: ArcLabelComponent<ComputedDatum<RawDatum>> | undefined
    arc_labels_component: Var[Any]
    # TS: number | undefined
    arc_labels_radius_offset: Var[int | float]
    # TS: number | undefined
    arc_labels_skip_angle: Var[int | float]
    # TS: number | undefined
    arc_labels_skip_radius: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_labels_text_color: Var[Any]
    # TS: PropertyAccessor<ComputedDatum<RawDatum>, string> | undefined
    arc_link_label: Var[Any]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_link_labels_color: Var[Any]
    # TS: number | undefined
    arc_link_labels_diagonal_length: Var[int | float]
    # TS: number | undefined
    arc_link_labels_offset: Var[int | float]
    # TS: number | undefined
    arc_link_labels_skip_angle: Var[int | float]
    # TS: number | undefined
    arc_link_labels_straight_length: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    arc_link_labels_text_color: Var[Any]
    # TS: number | undefined
    arc_link_labels_text_offset: Var[int | float]
    # TS: number | undefined
    arc_link_labels_thickness: Var[int | float]
    # TS: InheritedColorConfig<ComputedDatum<RawDatum>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: ArcLinkLabelComponent<ComputedDatum<RawDatum>> | undefined
    component: Var[Any]
    # TS: number | undefined
    corner_radius: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: DatumId | null | undefined
    default_active_id: Var[str | int | float | None]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_arc_labels: Var[bool]
    # TS: boolean | undefined
    enable_arc_link_labels: Var[bool]
    # TS: number | undefined
    end_angle: Var[int | float]
    # TS: boolean | undefined
    fit: Var[bool]
    # TS: ((data: LegendDatum<RawDatum>[]) => void) | undefined
    forward_legend_data: Var[Any]
    # Accessor for the datum id (nivo's `id` prop): a key name or JS function.
    id_by: Var[Any]
    # TS: number | undefined
    inner_radius: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | undefined
    pad_angle: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: boolean | undefined
    sort_by_value: Var[bool]
    # TS: number | undefined
    start_angle: Var[int | float]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<RawDatum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_active_id_change: EventHandler[nivo_event_spec]
    on_click: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


pie = Pie.create
pie_canvas = PieCanvas.create

__all__ = [
    "Pie",
    "PieCanvas",
    "pie",
    "pie_canvas",
]
