"""Stub file for custom_components/reflex_nivo/charts/pie.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

class Pie(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_id: Var[float | int | str | None] | float | int | str | None = None,
        active_inner_radius_offset: Var[float | int] | float | int | None = None,
        active_outer_radius_offset: Var[float | int] | float | int | None = None,
        animate: Var[bool] | bool | None = None,
        arc_label: Any | Var[Any] | None = None,
        arc_labels_component: Any | Var[Any] | None = None,
        arc_labels_radius_offset: Var[float | int] | float | int | None = None,
        arc_labels_skip_angle: Var[float | int] | float | int | None = None,
        arc_labels_skip_radius: Var[float | int] | float | int | None = None,
        arc_labels_text_color: Any | Var[Any] | None = None,
        arc_link_label: Any | Var[Any] | None = None,
        arc_link_label_component: Any | Var[Any] | None = None,
        arc_link_labels_color: Any | Var[Any] | None = None,
        arc_link_labels_diagonal_length: Var[float | int] | float | int | None = None,
        arc_link_labels_offset: Var[float | int] | float | int | None = None,
        arc_link_labels_skip_angle: Var[float | int] | float | int | None = None,
        arc_link_labels_straight_length: Var[float | int] | float | int | None = None,
        arc_link_labels_text_color: Any | Var[Any] | None = None,
        arc_link_labels_text_offset: Var[float | int] | float | int | None = None,
        arc_link_labels_thickness: Var[float | int] | float | int | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Var[float | int] | float | int | None = None,
        colors: Any | Var[Any] | None = None,
        component: Any | Var[Any] | None = None,
        corner_radius: Var[float | int] | float | int | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_active_id: Var[float | int | str | None]
        | float
        | int
        | str
        | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        enable_arc_labels: Var[bool] | bool | None = None,
        enable_arc_link_labels: Var[bool] | bool | None = None,
        end_angle: Var[float | int] | float | int | None = None,
        fill: Any | Var[Any] | None = None,
        fit: Var[bool] | bool | None = None,
        forward_legend_data: Any | Var[Any] | None = None,
        id_by: Any | Var[Any] | None = None,
        inner_radius: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        pad_angle: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        sort_by_value: Var[bool] | bool | None = None,
        start_angle: Var[float | int] | float | int | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        transition_mode: Literal[
            "centerRadius",
            "endAngle",
            "innerRadius",
            "middleAngle",
            "outerRadius",
            "pushIn",
            "pushOut",
            "startAngle",
        ]
        | Var[
            Literal[
                "centerRadius",
                "endAngle",
                "innerRadius",
                "middleAngle",
                "outerRadius",
                "pushIn",
                "pushOut",
                "startAngle",
            ]
        ]
        | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_active_id_change: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Pie":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_id: no description
            active_inner_radius_offset: no description
            active_outer_radius_offset: no description
            animate: no description
            arc_label: no description
            arc_labels_component: no description
            arc_labels_radius_offset: no description
            arc_labels_skip_angle: no description
            arc_labels_skip_radius: no description
            arc_labels_text_color: no description
            arc_link_label: no description
            arc_link_label_component: no description
            arc_link_labels_color: no description
            arc_link_labels_diagonal_length: no description
            arc_link_labels_offset: no description
            arc_link_labels_skip_angle: no description
            arc_link_labels_straight_length: no description
            arc_link_labels_text_color: no description
            arc_link_labels_text_offset: no description
            arc_link_labels_thickness: no description
            border_color: no description
            border_width: no description
            colors: no description
            component: no description
            corner_radius: no description
            data: no description
            debounce_resize: no description
            default_active_id: no description
            default_height: no description
            default_width: no description
            defs: no description
            enable_arc_labels: no description
            enable_arc_link_labels: no description
            end_angle: no description
            fill: no description
            fit: no description
            forward_legend_data: no description
            id_by: no description
            inner_radius: no description
            is_interactive: no description
            layers: no description
            legends: no description
            margin: no description
            motion_config: no description
            pad_angle: no description
            render_wrapper: no description
            role: no description
            sort_by_value: no description
            start_angle: no description
            theme: no description
            tooltip: no description
            transition_mode: no description
            value: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_active_id_change: no description
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class PieCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_id: Var[float | int | str | None] | float | int | str | None = None,
        active_inner_radius_offset: Var[float | int] | float | int | None = None,
        active_outer_radius_offset: Var[float | int] | float | int | None = None,
        arc_label: Any | Var[Any] | None = None,
        arc_labels_component: Any | Var[Any] | None = None,
        arc_labels_radius_offset: Var[float | int] | float | int | None = None,
        arc_labels_skip_angle: Var[float | int] | float | int | None = None,
        arc_labels_skip_radius: Var[float | int] | float | int | None = None,
        arc_labels_text_color: Any | Var[Any] | None = None,
        arc_link_label: Any | Var[Any] | None = None,
        arc_link_labels_color: Any | Var[Any] | None = None,
        arc_link_labels_diagonal_length: Var[float | int] | float | int | None = None,
        arc_link_labels_offset: Var[float | int] | float | int | None = None,
        arc_link_labels_skip_angle: Var[float | int] | float | int | None = None,
        arc_link_labels_straight_length: Var[float | int] | float | int | None = None,
        arc_link_labels_text_color: Any | Var[Any] | None = None,
        arc_link_labels_text_offset: Var[float | int] | float | int | None = None,
        arc_link_labels_thickness: Var[float | int] | float | int | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Var[float | int] | float | int | None = None,
        colors: Any | Var[Any] | None = None,
        component: Any | Var[Any] | None = None,
        corner_radius: Var[float | int] | float | int | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_active_id: Var[float | int | str | None]
        | float
        | int
        | str
        | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_arc_labels: Var[bool] | bool | None = None,
        enable_arc_link_labels: Var[bool] | bool | None = None,
        end_angle: Var[float | int] | float | int | None = None,
        fit: Var[bool] | bool | None = None,
        forward_legend_data: Any | Var[Any] | None = None,
        id_by: Any | Var[Any] | None = None,
        inner_radius: Var[float | int] | float | int | None = None,
        is_interactive: Var[bool] | bool | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        pad_angle: Var[float | int] | float | int | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        sort_by_value: Var[bool] | bool | None = None,
        start_angle: Var[float | int] | float | int | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_active_id_change: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PieCanvas":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_id: no description
            active_inner_radius_offset: no description
            active_outer_radius_offset: no description
            arc_label: no description
            arc_labels_component: no description
            arc_labels_radius_offset: no description
            arc_labels_skip_angle: no description
            arc_labels_skip_radius: no description
            arc_labels_text_color: no description
            arc_link_label: no description
            arc_link_labels_color: no description
            arc_link_labels_diagonal_length: no description
            arc_link_labels_offset: no description
            arc_link_labels_skip_angle: no description
            arc_link_labels_straight_length: no description
            arc_link_labels_text_color: no description
            arc_link_labels_text_offset: no description
            arc_link_labels_thickness: no description
            border_color: no description
            border_width: no description
            colors: no description
            component: no description
            corner_radius: no description
            data: no description
            debounce_resize: no description
            default_active_id: no description
            default_height: no description
            default_width: no description
            enable_arc_labels: no description
            enable_arc_link_labels: no description
            end_angle: no description
            fit: no description
            forward_legend_data: no description
            id_by: no description
            inner_radius: no description
            is_interactive: no description
            legends: no description
            margin: no description
            pad_angle: no description
            pixel_ratio: no description
            render_wrapper: no description
            role: no description
            sort_by_value: no description
            start_angle: no description
            theme: no description
            tooltip: no description
            value: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_active_id_change: no description
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

pie = Pie.create
pie_canvas = PieCanvas.create
__all__ = ["Pie", "PieCanvas", "pie", "pie_canvas"]
