"""Reflex wrappers for @nivo/radial-bar.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class RadialBar(NivoComponent):
    """Radial bar chart.

    Wraps ``ResponsiveRadialBar`` from ``@nivo/radial-bar``.
    Docs: https://nivo.rocks/radial-bar/
    """

    library = nivo_package("radial-bar")
    tag = "ResponsiveRadialBar"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<ComputedBar<D>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: CircularAxisConfig | null | undefined
    circular_axis_inner: Var[Any]
    # TS: CircularAxisConfig | null | undefined
    circular_axis_outer: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: number | undefined
    corner_radius: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_circular_grid: Var[bool]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    enable_radial_grid: Var[bool]
    # TS: boolean | undefined
    enable_tracks: Var[bool]
    # TS: number | undefined
    end_angle: Var[int | float]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: number | undefined
    inner_radius: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<ComputedBar<D>, string> | undefined
    label: Var[Any]
    # TS: number | undefined
    labels_radius_offset: Var[int | float]
    # TS: number | undefined
    labels_skip_angle: Var[int | float]
    # TS: number | undefined
    labels_skip_radius: Var[int | float]
    # TS: InheritedColorConfig<ComputedBar<D>> | undefined
    labels_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | "auto" | undefined
    max_value: Var[Literal["auto"] | int | float]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    pad_angle: Var[int | float]
    # TS: number | undefined
    padding: Var[int | float]
    # TS: RadialAxisConfig | null | undefined
    radial_axis_end: Var[Any]
    # TS: RadialAxisConfig | null | undefined
    radial_axis_start: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number | undefined
    start_angle: Var[int | float]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: string | undefined
    tracks_color: Var[str]
    # TS: "startAngle" | "endAngle" | "innerRadius" | "middleAngle" | "centerRadius" | "outerRadius" | "pushIn" | "pushO
    transition_mode: Var[Literal["startAngle", "endAngle", "innerRadius", "middleAngle", "centerRadius", "outerRadius", "pushIn", "pushOut"]]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


radial_bar = RadialBar.create

__all__ = [
    "RadialBar",
    "radial_bar",
]
