"""Reflex wrappers for @nivo/sankey.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class Sankey(NivoComponent):
    """Sankey diagram of flows between nodes.

    Wraps ``ResponsiveSankey`` from ``@nivo/sankey``.
    Docs: https://nivo.rocks/sankey/
    """

    library = nivo_package("sankey")
    tag = "ResponsiveSankey"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: SankeyAlignType | SankeyAlignFunction | undefined
    align: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_labels: Var[bool]
    # TS: boolean | undefined
    enable_link_gradient: Var[bool]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<SankeyNodeDatum<N, L>, "label" | "color">, string> | undefined
    label: Var[Any]
    # TS: SankeyLabelComponent<N, L> | undefined
    label_component: Var[Any]
    # TS: "horizontal" | "vertical" | undefined
    label_orientation: Var[Literal["horizontal", "vertical"]]
    # TS: number | undefined
    label_padding: Var[int | float]
    # TS: "inside" | "outside" | undefined
    label_position: Var[Literal["inside", "outside"]]
    # TS: InheritedColorConfig<SankeyNodeDatum<N, L>> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: "horizontal" | "vertical" | undefined
    layout: Var[Literal["horizontal", "vertical"]]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # TS: CssMixBlendMode | undefined
    link_blend_mode: Var[str]
    # TS: number | undefined
    link_contract: Var[int | float]
    # TS: number | undefined
    link_hover_opacity: Var[int | float]
    # TS: number | undefined
    link_hover_others_opacity: Var[int | float]
    # TS: number | undefined
    link_opacity: Var[int | float]
    # TS: FunctionComponent<{ link: SankeyLinkDatum<N, L>; }> | undefined
    link_tooltip: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: InheritedColorConfig<SankeyNodeDatum<N, L>> | undefined
    node_border_color: Var[Any]
    # TS: number | undefined
    node_border_radius: Var[int | float]
    # TS: number | undefined
    node_border_width: Var[int | float]
    # TS: number | undefined
    node_hover_opacity: Var[int | float]
    # TS: number | undefined
    node_hover_others_opacity: Var[int | float]
    # TS: number | undefined
    node_inner_padding: Var[int | float]
    # TS: number | undefined
    node_opacity: Var[int | float]
    # TS: number | undefined
    node_spacing: Var[int | float]
    # TS: number | undefined
    node_thickness: Var[int | float]
    # TS: FunctionComponent<{ node: SankeyNodeDatum<N, L>; }> | undefined
    node_tooltip: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: SankeySortType | SankeySortFunction<N, L> | undefined
    sort: Var[Any]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


sankey = Sankey.create

__all__ = [
    "Sankey",
    "sankey",
]
