"""Reflex wrappers for @nivo/scatterplot.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class ScatterPlot(NivoComponent):
    """Scatter plot of x/y series.

    Wraps ``ResponsiveScatterPlot`` from ``@nivo/scatterplot``.
    Docs: https://nivo.rocks/scatterplot/
    """

    library = nivo_package("scatterplot")
    tag = "ResponsiveScatterPlot"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # TS: CssMixBlendMode | undefined
    blend_mode: Var[str]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: GridValues<RawDatum["x"]> | undefined
    grid_x_values: Var[Any]
    # TS: GridValues<RawDatum["y"]> | undefined
    grid_y_values: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # Cartesian markers: [{'axis': 'y', 'value': 0, 'legend': '...'}].
    markers: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: ScatterPlotNode<RawDatum> | undefined
    node_component: Var[Any]
    # TS: PropertyAccessor<Omit<ScatterPlotNodeData<RawDatum>, "id" | "color" | "size">, string> | undefined
    node_id: Var[Any]
    # TS: number | ScatterPlotNodeDynamicSizeSpec | PropertyAccessor<Omit<ScatterPlotNodeData<RawDatum>, "color" | "size
    node_size: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]
    # TS: ValueFormat<RawDatum["x"]> | undefined
    x_format: Var[Any]
    # x scale spec, e.g. {'type': 'linear', 'min': 'auto'}.
    x_scale: Var[Any]
    # TS: ValueFormat<RawDatum["y"]> | undefined
    y_format: Var[Any]
    # y scale spec, e.g. {'type': 'linear', 'stacked': True}.
    y_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_mouse_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class ScatterPlotCanvas(NivoComponent):
    """Scatter plot rendered on canvas.

    Wraps ``ResponsiveScatterPlotCanvas`` from ``@nivo/scatterplot``.
    Docs: https://nivo.rocks/scatterplot/canvas/
    """

    library = nivo_package("scatterplot")
    tag = "ResponsiveScatterPlotCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Annotations: [{'type': 'circle', 'match': {...}, 'note': '...'}].
    annotations: Var[Any]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Bottom axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_bottom: Var[Any]
    # Left axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_left: Var[Any]
    # Right axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_right: Var[Any]
    # Top axis config dict, or None to hide (see reflex_nivo.axis()).
    axis_top: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_grid_x: Var[bool]
    # TS: boolean | undefined
    enable_grid_y: Var[bool]
    # TS: GridValues<RawDatum["x"]> | undefined
    grid_x_values: Var[Any]
    # TS: GridValues<RawDatum["y"]> | undefined
    grid_y_values: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: PropertyAccessor<Omit<ScatterPlotNodeData<RawDatum>, "id" | "color" | "size">, string> | undefined
    node_id: Var[Any]
    # TS: number | ScatterPlotNodeDynamicSizeSpec | PropertyAccessor<Omit<ScatterPlotNodeData<RawDatum>, "color" | "size
    node_size: Var[Any]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: ((ctx: CanvasRenderingContext2D, node: ScatterPlotNodeData<RawDatum>) => void) | undefined
    render_node: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]
    # TS: ValueFormat<RawDatum["x"]> | undefined
    x_format: Var[Any]
    # x scale spec, e.g. {'type': 'linear', 'min': 'auto'}.
    x_scale: Var[Any]
    # TS: ValueFormat<RawDatum["y"]> | undefined
    y_format: Var[Any]
    # y scale spec, e.g. {'type': 'linear', 'stacked': True}.
    y_scale: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_double_click: EventHandler[nivo_event_spec]
    on_mouse_down: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


scatterplot = ScatterPlot.create
scatterplot_canvas = ScatterPlotCanvas.create

__all__ = [
    "ScatterPlot",
    "ScatterPlotCanvas",
    "scatterplot",
    "scatterplot_canvas",
]
