"""Stub file for custom_components/reflex_nivo/charts/stream.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

class Stream(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        axis_bottom: Any | Var[Any] | None = None,
        axis_left: Any | Var[Any] | None = None,
        axis_right: Any | Var[Any] | None = None,
        axis_top: Any | Var[Any] | None = None,
        border_color: Any | Var[Any] | None = None,
        border_width: Var[float | int] | float | int | None = None,
        colors: Any | Var[Any] | None = None,
        curve: Var[str] | str | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        dot_border_color: Any | Var[Any] | None = None,
        dot_border_width: Any | Var[Any] | None = None,
        dot_color: Any | Var[Any] | None = None,
        dot_component: Any | Var[Any] | None = None,
        dot_position: Literal["center", "end", "start"]
        | Var[Literal["center", "end", "start"]]
        | None = None,
        dot_size: Any | Var[Any] | None = None,
        enable_dots: Var[bool] | bool | None = None,
        enable_grid_x: Var[bool] | bool | None = None,
        enable_grid_y: Var[bool] | bool | None = None,
        enable_stack_tooltip: Var[bool] | bool | None = None,
        fill: Any | Var[Any] | None = None,
        fill_opacity: Var[float | int] | float | int | None = None,
        grid_x_values: Any | Var[Any] | None = None,
        grid_y_values: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        keys: Any | Var[Any] | None = None,
        label: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        offset_type: Any | Var[Any] | None = None,
        order: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        stack: Any | Var[Any] | None = None,
        stack_tooltip: Any | Var[Any] | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Stream":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            axis_bottom: no description
            axis_left: no description
            axis_right: no description
            axis_top: no description
            border_color: no description
            border_width: no description
            colors: no description
            curve: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            defs: no description
            dot_border_color: no description
            dot_border_width: no description
            dot_color: no description
            dot_component: no description
            dot_position: no description
            dot_size: no description
            enable_dots: no description
            enable_grid_x: no description
            enable_grid_y: no description
            enable_stack_tooltip: no description
            fill: no description
            fill_opacity: no description
            grid_x_values: no description
            grid_y_values: no description
            is_interactive: no description
            keys: no description
            label: no description
            layers: no description
            legends: no description
            margin: no description
            motion_config: no description
            offset_type: no description
            order: no description
            render_wrapper: no description
            role: no description
            stack: no description
            stack_tooltip: no description
            theme: no description
            tooltip: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

stream = Stream.create
__all__ = ["Stream", "stream"]
