"""Reflex wrappers for @nivo/treemap.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class TreeMap(NivoComponent):
    """Treemap of hierarchical data.

    Wraps ``ResponsiveTreeMap`` from ``@nivo/treemap``.
    Docs: https://nivo.rocks/treemap/
    """

    library = nivo_package("treemap")
    tag = "ResponsiveTreeMap"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: string | DatumIdentityAccessor<ComputedNodeWithoutStyles<Datum>> | undefined
    color_by: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: boolean | undefined
    enable_parent_label: Var[bool]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<ComputedNodeWithoutStyles<Datum>, "label" | "parentLabel">, string> | undefined
    label: Var[Any]
    # TS: ValueFormat<number> | undefined
    label_format: Var[Any]
    # TS: number | undefined
    label_skip_size: Var[int | float]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: boolean | undefined
    leaves_only: Var[bool]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: NodeComponent<Datum> | undefined
    node_component: Var[Any]
    # TS: number | undefined
    node_opacity: Var[int | float]
    # TS: boolean | undefined
    orient_label: Var[bool]
    # TS: number | undefined
    outer_padding: Var[int | float]
    # TS: PropertyAccessor<Omit<ComputedNodeWithoutStyles<Datum>, "parentLabel">, string> | undefined
    parent_label: Var[Any]
    # TS: number | undefined
    parent_label_padding: Var[int | float]
    # TS: "bottom" | "left" | "right" | "top" | undefined
    parent_label_position: Var[Literal["bottom", "left", "right", "top"]]
    # TS: number | undefined
    parent_label_size: Var[int | float]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    parent_label_text_color: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: "binary" | "dice" | "slice" | "sliceDice" | "squarify" | undefined
    tile: Var[Literal["binary", "dice", "slice", "sliceDice", "squarify"]]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<Datum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class TreeMapCanvas(NivoComponent):
    """Treemap rendered on canvas.

    Wraps ``ResponsiveTreeMapCanvas`` from ``@nivo/treemap``.
    Docs: https://nivo.rocks/treemap/canvas/
    """

    library = nivo_package("treemap")
    tag = "ResponsiveTreeMapCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: string | DatumIdentityAccessor<ComputedNodeWithoutStyles<Datum>> | undefined
    color_by: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<ComputedNodeWithoutStyles<Datum>, "label" | "parentLabel">, string> | undefined
    label: Var[Any]
    # TS: ValueFormat<number> | undefined
    label_format: Var[Any]
    # TS: number | undefined
    label_skip_size: Var[int | float]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: boolean | undefined
    leaves_only: Var[bool]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    node_opacity: Var[int | float]
    # TS: boolean | undefined
    orient_label: Var[bool]
    # TS: number | undefined
    outer_padding: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: "binary" | "dice" | "slice" | "sliceDice" | "squarify" | undefined
    tile: Var[Literal["binary", "dice", "slice", "sliceDice", "squarify"]]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<Datum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class TreeMapHtml(NivoComponent):
    """Treemap rendered with HTML elements.

    Wraps ``ResponsiveTreeMapHtml`` from ``@nivo/treemap``.
    Docs: https://nivo.rocks/treemap/html/
    """

    library = nivo_package("treemap")
    tag = "ResponsiveTreeMapHtml"
    _nivo_variant: ClassVar[str] = "html"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: string | DatumIdentityAccessor<ComputedNodeWithoutStyles<Datum>> | undefined
    color_by: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: boolean | undefined
    enable_parent_label: Var[bool]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: number | undefined
    inner_padding: Var[int | float]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<Omit<ComputedNodeWithoutStyles<Datum>, "label" | "parentLabel">, string> | undefined
    label: Var[Any]
    # TS: ValueFormat<number> | undefined
    label_format: Var[Any]
    # TS: number | undefined
    label_skip_size: Var[int | float]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    label_text_color: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: boolean | undefined
    leaves_only: Var[bool]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: NodeComponent<Datum> | undefined
    node_component: Var[Any]
    # TS: number | undefined
    node_opacity: Var[int | float]
    # TS: boolean | undefined
    orient_label: Var[bool]
    # TS: number | undefined
    outer_padding: Var[int | float]
    # TS: PropertyAccessor<Omit<ComputedNodeWithoutStyles<Datum>, "parentLabel">, string> | undefined
    parent_label: Var[Any]
    # TS: number | undefined
    parent_label_padding: Var[int | float]
    # TS: "bottom" | "left" | "right" | "top" | undefined
    parent_label_position: Var[Literal["bottom", "left", "right", "top"]]
    # TS: number | undefined
    parent_label_size: Var[int | float]
    # TS: InheritedColorConfig<ComputedNodeWithoutStyles<Datum> & { color: string; }> | undefined
    parent_label_text_color: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: "binary" | "dice" | "slice" | "sliceDice" | "squarify" | undefined
    tile: Var[Literal["binary", "dice", "slice", "sliceDice", "squarify"]]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: PropertyAccessor<Datum, number> | undefined
    value: Var[Any]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


treemap = TreeMap.create
treemap_canvas = TreeMapCanvas.create
treemap_html = TreeMapHtml.create

__all__ = [
    "TreeMap",
    "TreeMapCanvas",
    "TreeMapHtml",
    "treemap",
    "treemap_canvas",
    "treemap_html",
]
