"""Stub file for custom_components/reflex_nivo/charts/tree.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

from reflex.components.component import Component


class Tree(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_link_thickness: Any | Var[Any] | None = None,
        active_node_size: Any | Var[Any] | None = None,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        debug_mesh: Var[bool] | bool | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_label: Var[bool] | bool | None = None,
        fix_node_color_at_depth: Var[float | int] | float | int | None = None,
        highlight_ancestor_links: Var[bool] | bool | None = None,
        highlight_ancestor_nodes: Var[bool] | bool | None = None,
        highlight_descendant_links: Var[bool] | bool | None = None,
        highlight_descendant_nodes: Var[bool] | bool | None = None,
        identity: Any | Var[Any] | None = None,
        inactive_link_thickness: Any | Var[Any] | None = None,
        inactive_node_size: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        label_component: Any | Var[Any] | None = None,
        label_offset: Var[float | int] | float | int | None = None,
        labels_position: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        layout: Any | Var[Any] | None = None,
        link_color: Any | Var[Any] | None = None,
        link_component: Any | Var[Any] | None = None,
        link_curve: Any | Var[Any] | None = None,
        link_thickness: Any | Var[Any] | None = None,
        link_tooltip: Any | Var[Any] | None = None,
        link_tooltip_anchor: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        mesh_detection_radius: Var[float | int] | float | int | None = None,
        mode: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        node_color: Any | Var[Any] | None = None,
        node_component: Any | Var[Any] | None = None,
        node_size: Any | Var[Any] | None = None,
        node_tooltip: Any | Var[Any] | None = None,
        node_tooltip_anchor: Any | Var[Any] | None = None,
        node_tooltip_position: Any | Var[Any] | None = None,
        orient_label: Var[bool] | bool | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        use_mesh: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_link_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_link_double_click: Optional[
            EventType[()] | EventType[dict[str, Any]]
        ] = None,
        on_link_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_link_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_link_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_link_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_link_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_node_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_double_click: Optional[
            EventType[()] | EventType[dict[str, Any]]
        ] = None,
        on_node_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_link_thickness: no description
            active_node_size: no description
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            data: no description
            debounce_resize: no description
            debug_mesh: no description
            default_height: no description
            default_width: no description
            enable_label: no description
            fix_node_color_at_depth: no description
            highlight_ancestor_links: no description
            highlight_ancestor_nodes: no description
            highlight_descendant_links: no description
            highlight_descendant_nodes: no description
            identity: no description
            inactive_link_thickness: no description
            inactive_node_size: no description
            is_interactive: no description
            label: no description
            label_component: no description
            label_offset: no description
            labels_position: no description
            layers: no description
            layout: no description
            link_color: no description
            link_component: no description
            link_curve: no description
            link_thickness: no description
            link_tooltip: no description
            link_tooltip_anchor: no description
            margin: no description
            mesh_detection_radius: no description
            mode: no description
            motion_config: no description
            node_color: no description
            node_component: no description
            node_size: no description
            node_tooltip: no description
            node_tooltip_anchor: no description
            node_tooltip_position: no description
            orient_label: no description
            render_wrapper: no description
            role: no description
            theme: no description
            use_mesh: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_link_click: no description
            on_link_double_click: no description
            on_link_mouse_down: no description
            on_link_mouse_enter: no description
            on_link_mouse_leave: no description
            on_link_mouse_move: no description
            on_link_mouse_up: no description
            on_node_click: no description
            on_node_double_click: no description
            on_node_mouse_down: no description
            on_node_mouse_enter: no description
            on_node_mouse_leave: no description
            on_node_mouse_move: no description
            on_node_mouse_up: no description
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class TreeCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        active_link_thickness: Any | Var[Any] | None = None,
        active_node_size: Any | Var[Any] | None = None,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        debug_mesh: Var[bool] | bool | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        enable_label: Var[bool] | bool | None = None,
        fix_node_color_at_depth: Var[float | int] | float | int | None = None,
        highlight_ancestor_links: Var[bool] | bool | None = None,
        highlight_ancestor_nodes: Var[bool] | bool | None = None,
        highlight_descendant_links: Var[bool] | bool | None = None,
        highlight_descendant_nodes: Var[bool] | bool | None = None,
        identity: Any | Var[Any] | None = None,
        inactive_link_thickness: Any | Var[Any] | None = None,
        inactive_node_size: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        label: Any | Var[Any] | None = None,
        label_offset: Var[float | int] | float | int | None = None,
        labels_position: Any | Var[Any] | None = None,
        layers: Any | Var[Any] | None = None,
        layout: Any | Var[Any] | None = None,
        link_color: Any | Var[Any] | None = None,
        link_curve: Any | Var[Any] | None = None,
        link_thickness: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        mesh_detection_radius: Var[float | int] | float | int | None = None,
        mode: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        node_color: Any | Var[Any] | None = None,
        node_size: Any | Var[Any] | None = None,
        node_tooltip: Any | Var[Any] | None = None,
        node_tooltip_anchor: Any | Var[Any] | None = None,
        node_tooltip_position: Any | Var[Any] | None = None,
        orient_label: Var[bool] | bool | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        render_label: Any | Var[Any] | None = None,
        render_link: Any | Var[Any] | None = None,
        render_node: Any | Var[Any] | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        use_mesh: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_node_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_double_click: Optional[
            EventType[()] | EventType[dict[str, Any]]
        ] = None,
        on_node_mouse_down: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_node_mouse_up: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> Component:
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            active_link_thickness: no description
            active_node_size: no description
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            data: no description
            debounce_resize: no description
            debug_mesh: no description
            default_height: no description
            default_width: no description
            enable_label: no description
            fix_node_color_at_depth: no description
            highlight_ancestor_links: no description
            highlight_ancestor_nodes: no description
            highlight_descendant_links: no description
            highlight_descendant_nodes: no description
            identity: no description
            inactive_link_thickness: no description
            inactive_node_size: no description
            is_interactive: no description
            label: no description
            label_offset: no description
            labels_position: no description
            layers: no description
            layout: no description
            link_color: no description
            link_curve: no description
            link_thickness: no description
            margin: no description
            mesh_detection_radius: no description
            mode: no description
            motion_config: no description
            node_color: no description
            node_size: no description
            node_tooltip: no description
            node_tooltip_anchor: no description
            node_tooltip_position: no description
            orient_label: no description
            pixel_ratio: no description
            render_label: no description
            render_link: no description
            render_node: no description
            render_wrapper: no description
            role: no description
            theme: no description
            use_mesh: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_node_click: no description
            on_node_double_click: no description
            on_node_mouse_down: no description
            on_node_mouse_enter: no description
            on_node_mouse_leave: no description
            on_node_mouse_move: no description
            on_node_mouse_up: no description
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

tree = Tree.create
tree_canvas = TreeCanvas.create
__all__ = ["Tree", "TreeCanvas", "tree", "tree_canvas"]
