"""Reflex wrappers for @nivo/tree.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec, nivo_id_event_spec
from ..constants import nivo_package


class Tree(NivoComponent):
    """Tree / dendrogram layout of hierarchical data.

    Wraps ``ResponsiveTree`` from ``@nivo/tree``.
    Docs: https://nivo.rocks/tree/
    """

    library = nivo_package("tree")
    tag = "ResponsiveTree"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: number | LinkThicknessModifierFunction<Datum> | undefined
    active_link_thickness: Var[Any]
    # TS: number | NodeSizeModifierFunction<Datum> | undefined
    active_node_size: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: number | undefined
    fix_node_color_at_depth: Var[int | float]
    # TS: boolean | undefined
    highlight_ancestor_links: Var[bool]
    # TS: boolean | undefined
    highlight_ancestor_nodes: Var[bool]
    # TS: boolean | undefined
    highlight_descendant_links: Var[bool]
    # TS: boolean | undefined
    highlight_descendant_nodes: Var[bool]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: number | LinkThicknessModifierFunction<Datum> | undefined
    inactive_link_thickness: Var[Any]
    # TS: number | NodeSizeModifierFunction<Datum> | undefined
    inactive_node_size: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<ComputedNode<Datum>, string> | undefined
    label: Var[Any]
    # TS: LabelComponent<Datum> | undefined
    label_component: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: LabelsPosition | undefined
    labels_position: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: Layout | undefined
    layout: Var[Any]
    # TS: InheritedColorConfig<IntermediateComputedLink<Datum>> | undefined
    link_color: Var[Any]
    # TS: LinkComponent<Datum> | undefined
    link_component: Var[Any]
    # TS: LinkCurve | undefined
    link_curve: Var[Any]
    # TS: number | LinkThicknessFunction<Datum> | undefined
    link_thickness: Var[Any]
    # TS: LinkTooltip<Datum> | undefined
    link_tooltip: Var[Any]
    # TS: TooltipAnchor | undefined
    link_tooltip_anchor: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | undefined
    mesh_detection_radius: Var[int | float]
    # TS: TreeMode | undefined
    mode: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: OrdinalColorScaleConfig<IntermediateComputedNode<Datum>> | undefined
    node_color: Var[Any]
    # TS: NodeComponent<Datum> | undefined
    node_component: Var[Any]
    # TS: number | NodeSizeFunction<Datum> | undefined
    node_size: Var[Any]
    # TS: NodeTooltip<Datum> | undefined
    node_tooltip: Var[Any]
    # TS: TooltipAnchor | undefined
    node_tooltip_anchor: Var[Any]
    # TS: TooltipPosition | undefined
    node_tooltip_position: Var[Any]
    # TS: boolean | undefined
    orient_label: Var[bool]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]

    # Events: the handler receives the JSON-safe first callback argument.
    on_link_click: EventHandler[nivo_event_spec]
    on_link_double_click: EventHandler[nivo_event_spec]
    on_link_mouse_down: EventHandler[nivo_event_spec]
    on_link_mouse_enter: EventHandler[nivo_event_spec]
    on_link_mouse_leave: EventHandler[nivo_event_spec]
    on_link_mouse_move: EventHandler[nivo_event_spec]
    on_link_mouse_up: EventHandler[nivo_event_spec]
    on_node_click: EventHandler[nivo_event_spec]
    on_node_double_click: EventHandler[nivo_event_spec]
    on_node_mouse_down: EventHandler[nivo_event_spec]
    on_node_mouse_enter: EventHandler[nivo_event_spec]
    on_node_mouse_leave: EventHandler[nivo_event_spec]
    on_node_mouse_move: EventHandler[nivo_event_spec]
    on_node_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class TreeCanvas(NivoComponent):
    """Tree layout rendered on canvas.

    Wraps ``ResponsiveTreeCanvas`` from ``@nivo/tree``.
    Docs: https://nivo.rocks/tree/canvas/
    """

    library = nivo_package("tree")
    tag = "ResponsiveTreeCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # TS: number | LinkThicknessModifierFunction<Datum> | undefined
    active_link_thickness: Var[Any]
    # TS: number | NodeSizeModifierFunction<Datum> | undefined
    active_node_size: Var[Any]
    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # TS: boolean | undefined
    debug_mesh: Var[bool]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_label: Var[bool]
    # TS: number | undefined
    fix_node_color_at_depth: Var[int | float]
    # TS: boolean | undefined
    highlight_ancestor_links: Var[bool]
    # TS: boolean | undefined
    highlight_ancestor_nodes: Var[bool]
    # TS: boolean | undefined
    highlight_descendant_links: Var[bool]
    # TS: boolean | undefined
    highlight_descendant_nodes: Var[bool]
    # TS: PropertyAccessor<Datum, string> | undefined
    identity: Var[Any]
    # TS: number | LinkThicknessModifierFunction<Datum> | undefined
    inactive_link_thickness: Var[Any]
    # TS: number | NodeSizeModifierFunction<Datum> | undefined
    inactive_node_size: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # TS: PropertyAccessor<ComputedNode<Datum>, string> | undefined
    label: Var[Any]
    # TS: number | undefined
    label_offset: Var[int | float]
    # TS: LabelsPosition | undefined
    labels_position: Var[Any]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: Layout | undefined
    layout: Var[Any]
    # TS: InheritedColorConfig<IntermediateComputedLink<Datum>> | undefined
    link_color: Var[Any]
    # TS: LinkCurve | undefined
    link_curve: Var[Any]
    # TS: number | LinkThicknessFunction<Datum> | undefined
    link_thickness: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: number | undefined
    mesh_detection_radius: Var[int | float]
    # TS: TreeMode | undefined
    mode: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: OrdinalColorScaleConfig<IntermediateComputedNode<Datum>> | undefined
    node_color: Var[Any]
    # TS: number | NodeSizeFunction<Datum> | undefined
    node_size: Var[Any]
    # TS: NodeTooltip<Datum> | undefined
    node_tooltip: Var[Any]
    # TS: TooltipAnchor | undefined
    node_tooltip_anchor: Var[Any]
    # TS: TooltipPosition | undefined
    node_tooltip_position: Var[Any]
    # TS: boolean | undefined
    orient_label: Var[bool]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # TS: LabelCanvasRenderer<Datum> | undefined
    render_label: Var[Any]
    # TS: LinkCanvasRenderer<Datum> | undefined
    render_link: Var[Any]
    # TS: NodeCanvasRenderer<Datum> | undefined
    render_node: Var[Any]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: boolean | undefined
    use_mesh: Var[bool]

    # Events: the handler receives the JSON-safe first callback argument.
    on_node_click: EventHandler[nivo_event_spec]
    on_node_double_click: EventHandler[nivo_event_spec]
    on_node_mouse_down: EventHandler[nivo_event_spec]
    on_node_mouse_enter: EventHandler[nivo_event_spec]
    on_node_mouse_leave: EventHandler[nivo_event_spec]
    on_node_mouse_move: EventHandler[nivo_event_spec]
    on_node_mouse_up: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


tree = Tree.create
tree_canvas = TreeCanvas.create

__all__ = [
    "Tree",
    "TreeCanvas",
    "tree",
    "tree_canvas",
]
