"""Reflex wrappers for @nivo/voronoi.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Voronoi(NivoComponent):
    """Voronoi tessellation of points.

    Wraps ``ResponsiveVoronoi`` from ``@nivo/voronoi``.
    Docs: https://nivo.rocks/voronoi/
    """

    library = nivo_package("voronoi")
    tag = "ResponsiveVoronoi"
    _nivo_variant: ClassVar[str] = "svg"

    # TS: string | undefined
    cell_line_color: Var[str]
    # TS: number | undefined
    cell_line_width: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: boolean | undefined
    enable_cells: Var[bool]
    # TS: boolean | undefined
    enable_links: Var[bool]
    # TS: boolean | undefined
    enable_points: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # TS: string | undefined
    link_line_color: Var[str]
    # TS: number | undefined
    link_line_width: Var[int | float]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # TS: string | undefined
    point_color: Var[str]
    # TS: number | undefined
    point_size: Var[int | float]
    # ARIA role of the chart root.
    role: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # TS: VoronoiDomain | undefined
    x_domain: Var[Any]
    # TS: VoronoiDomain | undefined
    y_domain: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_resize: EventHandler[nivo_event_spec]


voronoi = Voronoi.create

__all__ = [
    "Voronoi",
    "voronoi",
]
