"""Stub file for custom_components/reflex_nivo/charts/waffle.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ..base import NivoComponent

class Waffle(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Var[float | int] | float | int | None = None,
        border_width: Var[float | int] | float | int | None = None,
        cell_component: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        columns: Var[float | int] | float | int | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        defs: Any | Var[Any] | None = None,
        empty_color: Var[str] | str | None = None,
        empty_opacity: Var[float | int] | float | int | None = None,
        fill: Any | Var[Any] | None = None,
        fill_direction: Any | Var[Any] | None = None,
        forward_legend_data: Any | Var[Any] | None = None,
        hidden_ids: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        motion_stagger: Var[float | int] | float | int | None = None,
        padding: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        rows: Var[float | int] | float | int | None = None,
        test_id_prefix: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        total: Var[float | int] | float | int | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Waffle":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            cell_component: no description
            colors: no description
            columns: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            defs: no description
            empty_color: no description
            empty_opacity: no description
            fill: no description
            fill_direction: no description
            forward_legend_data: no description
            hidden_ids: no description
            is_interactive: no description
            layers: no description
            legends: no description
            margin: no description
            motion_config: no description
            motion_stagger: no description
            padding: no description
            render_wrapper: no description
            role: no description
            rows: no description
            test_id_prefix: no description
            theme: no description
            tooltip: no description
            total: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class WaffleCanvas(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Var[float | int] | float | int | None = None,
        border_width: Var[float | int] | float | int | None = None,
        colors: Any | Var[Any] | None = None,
        columns: Var[float | int] | float | int | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        empty_color: Var[str] | str | None = None,
        empty_opacity: Var[float | int] | float | int | None = None,
        fill_direction: Any | Var[Any] | None = None,
        forward_legend_data: Any | Var[Any] | None = None,
        hidden_ids: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        legends: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        padding: Var[float | int] | float | int | None = None,
        pixel_ratio: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        rows: Var[float | int] | float | int | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        total: Var[float | int] | float | int | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WaffleCanvas":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            colors: no description
            columns: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            empty_color: no description
            empty_opacity: no description
            fill_direction: no description
            forward_legend_data: no description
            hidden_ids: no description
            is_interactive: no description
            legends: no description
            margin: no description
            motion_config: no description
            padding: no description
            pixel_ratio: no description
            render_wrapper: no description
            role: no description
            rows: no description
            theme: no description
            tooltip: no description
            total: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

class WaffleHtml(NivoComponent):
    @classmethod
    def create(
        cls,
        *children,
        animate: Var[bool] | bool | None = None,
        aria_described_by: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        aria_labelled_by: Var[str] | str | None = None,
        border_color: Any | Var[Any] | None = None,
        border_radius: Var[float | int] | float | int | None = None,
        border_width: Var[float | int] | float | int | None = None,
        cell_component: Any | Var[Any] | None = None,
        colors: Any | Var[Any] | None = None,
        columns: Var[float | int] | float | int | None = None,
        data: Any | Var[Any] | None = None,
        debounce_resize: Var[float | int] | float | int | None = None,
        default_height: Var[float | int] | float | int | None = None,
        default_width: Var[float | int] | float | int | None = None,
        empty_color: Var[str] | str | None = None,
        empty_opacity: Var[float | int] | float | int | None = None,
        fill_direction: Any | Var[Any] | None = None,
        forward_legend_data: Any | Var[Any] | None = None,
        hidden_ids: Any | Var[Any] | None = None,
        is_interactive: Var[bool] | bool | None = None,
        layers: Any | Var[Any] | None = None,
        margin: Any | Var[Any] | None = None,
        motion_config: Any | Var[Any] | None = None,
        motion_stagger: Var[float | int] | float | int | None = None,
        padding: Var[float | int] | float | int | None = None,
        render_wrapper: Var[bool] | bool | None = None,
        role: Var[str] | str | None = None,
        rows: Var[float | int] | float | int | None = None,
        test_id_prefix: Var[str] | str | None = None,
        theme: Any | Var[Any] | None = None,
        tooltip: Any | Var[Any] | None = None,
        total: Var[float | int] | float | int | None = None,
        value_format: Any | Var[Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_leave: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_move: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_resize: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WaffleHtml":
        """Create the chart wrapped in a sized container.

        Args:
            *children: Ignored by nivo; accepted for API symmetry.
            animate: no description
            aria_described_by: no description
            aria_label: no description
            aria_labelled_by: no description
            border_color: no description
            border_radius: no description
            border_width: no description
            cell_component: no description
            colors: no description
            columns: no description
            data: no description
            debounce_resize: no description
            default_height: no description
            default_width: no description
            empty_color: no description
            empty_opacity: no description
            fill_direction: no description
            forward_legend_data: no description
            hidden_ids: no description
            is_interactive: no description
            layers: no description
            margin: no description
            motion_config: no description
            motion_stagger: no description
            padding: no description
            render_wrapper: no description
            role: no description
            rows: no description
            test_id_prefix: no description
            theme: no description
            tooltip: no description
            total: no description
            value_format: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_resize: no description
            **props: nivo props/events (snake_case) plus container props.

        Returns:
            A ``<div>`` containing the nivo chart.
        """
        ...

waffle = Waffle.create
waffle_canvas = WaffleCanvas.create
waffle_html = WaffleHtml.create
__all__ = [
    "Waffle",
    "WaffleCanvas",
    "WaffleHtml",
    "waffle",
    "waffle_canvas",
    "waffle_html",
]
