"""Reflex wrappers for @nivo/waffle.

Generated by scripts/generate_components.py -- do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, ClassVar, Literal

from reflex.event import EventHandler
from reflex.vars.base import Var

from ..base import NivoComponent, nivo_event_spec
from ..constants import nivo_package


class Waffle(NivoComponent):
    """Waffle chart of proportions on a grid.

    Wraps ``ResponsiveWaffle`` from ``@nivo/waffle``.
    Docs: https://nivo.rocks/waffle/
    """

    library = nivo_package("waffle")
    tag = "ResponsiveWaffle"
    _nivo_variant: ClassVar[str] = "svg"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<ComputedDatum<D> | { color: string; }> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: CellComponent<D> | undefined
    cell_component: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: number (required)
    columns: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # SVG pattern/gradient definitions (see reflex_nivo.pattern_dots_def & co).
    defs: Var[Any]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: number | undefined
    empty_opacity: Var[int | float]
    # Rules matching data to defs: [{'match': {'id': 'x'}, 'id': 'dots'}].
    fill: Var[Any]
    # TS: GridFillDirection | undefined
    fill_direction: Var[Any]
    # TS: ((data: LegendDatum<D>[]) => void) | undefined
    forward_legend_data: Var[Any]
    # TS: readonly D["id"][] | undefined
    hidden_ids: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    motion_stagger: Var[int | float]
    # TS: number | undefined
    padding: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number (required)
    rows: Var[int | float]
    # TS: string | undefined
    test_id_prefix: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: number (required)
    total: Var[int | float]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class WaffleCanvas(NivoComponent):
    """Waffle chart rendered on canvas.

    Wraps ``ResponsiveWaffleCanvas`` from ``@nivo/waffle``.
    Docs: https://nivo.rocks/waffle/canvas/
    """

    library = nivo_package("waffle")
    tag = "ResponsiveWaffleCanvas"
    _nivo_variant: ClassVar[str] = "canvas"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<{ color: string; } | ComputedDatum<D>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: number (required)
    columns: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: number | undefined
    empty_opacity: Var[int | float]
    # TS: GridFillDirection | undefined
    fill_direction: Var[Any]
    # TS: ((data: LegendDatum<D>[]) => void) | undefined
    forward_legend_data: Var[Any]
    # TS: readonly D["id"][] | undefined
    hidden_ids: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Legends configuration (see reflex_nivo.legend()).
    legends: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    padding: Var[int | float]
    # Canvas pixel ratio (defaults to window.devicePixelRatio).
    pixel_ratio: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number (required)
    rows: Var[int | float]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: number (required)
    total: Var[int | float]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


class WaffleHtml(NivoComponent):
    """Waffle chart rendered with HTML elements.

    Wraps ``ResponsiveWaffleHtml`` from ``@nivo/waffle``.
    Docs: https://nivo.rocks/waffle/html/
    """

    library = nivo_package("waffle")
    tag = "ResponsiveWaffleHtml"
    _nivo_variant: ClassVar[str] = "html"

    # Enable/disable transitions.
    animate: Var[bool]
    # TS: string | undefined
    aria_described_by: Var[str]
    # TS: string | undefined
    aria_label: Var[str]
    # TS: string | undefined
    aria_labelled_by: Var[str]
    # TS: InheritedColorConfig<{ color: string; } | ComputedDatum<RawDatum>> | undefined
    border_color: Var[Any]
    # TS: number | undefined
    border_radius: Var[int | float]
    # TS: number | undefined
    border_width: Var[int | float]
    # TS: CellComponent<RawDatum> | undefined
    cell_component: Var[Any]
    # Colors: {'scheme': 'nivo'}, a list of colors, a color, or a JS function.
    colors: Var[Any]
    # TS: number (required)
    columns: Var[int | float]
    # Chart data (see the nivo docs of this chart for the expected shape). (required)
    data: Var[Any]
    # Debounce (ms) applied to container resize detection.
    debounce_resize: Var[int | float]
    # Height used before the container has been measured.
    default_height: Var[int | float]
    # Width used before the container has been measured.
    default_width: Var[int | float]
    # TS: string | undefined
    empty_color: Var[str]
    # TS: number | undefined
    empty_opacity: Var[int | float]
    # TS: GridFillDirection | undefined
    fill_direction: Var[Any]
    # TS: ((data: LegendDatum<RawDatum>[]) => void) | undefined
    forward_legend_data: Var[Any]
    # TS: readonly RawDatum["id"][] | undefined
    hidden_ids: Var[Any]
    # Enable tooltips and mouse events.
    is_interactive: Var[bool]
    # Layers to render, in order (strings or custom JS layers).
    layers: Var[Any]
    # Chart margin: {'top': .., 'right': .., 'bottom': .., 'left': ..}.
    margin: Var[Any]
    # react-spring preset ('gentle', 'wobbly', ...) or a config dict.
    motion_config: Var[Any]
    # TS: number | undefined
    motion_stagger: Var[int | float]
    # TS: number | undefined
    padding: Var[int | float]
    # Render the wrapping div nivo uses for tooltips.
    render_wrapper: Var[bool]
    # ARIA role of the chart root.
    role: Var[str]
    # TS: number (required)
    rows: Var[int | float]
    # TS: string | undefined
    test_id_prefix: Var[str]
    # nivo theme; defaults to reflex_nivo.themes.auto() (follows color mode).
    theme: Var[Any]
    # Tooltip component: use reflex_nivo.tooltip('{template}') or reflex_nivo.js(...).
    tooltip: Var[Any]
    # TS: number (required)
    total: Var[int | float]
    # d3-format specifier (e.g. ' >-.2f') or JS function.
    value_format: Var[Any]

    # Events: the handler receives the JSON-safe first callback argument.
    on_click: EventHandler[nivo_event_spec]
    on_mouse_enter: EventHandler[nivo_event_spec]
    on_mouse_leave: EventHandler[nivo_event_spec]
    on_mouse_move: EventHandler[nivo_event_spec]
    on_resize: EventHandler[nivo_event_spec]


waffle = Waffle.create
waffle_canvas = WaffleCanvas.create
waffle_html = WaffleHtml.create

__all__ = [
    "Waffle",
    "WaffleCanvas",
    "WaffleHtml",
    "waffle",
    "waffle_canvas",
    "waffle_html",
]
